// Parsed from https://github.com/disclose/bug-bounty-platforms (README.md tables),
// which is itself a community-maintained, CC0-licensed open catalog.
// Update by re-running the same parse against the upstream README when it changes —
// see CONTRIBUTING.md for the source repo link.
const platforms = [
  {
    name: 'Australian Government VDP',
    url: 'https://www.homeaffairs.gov.au',
    region: 'Australia',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'bugbounty.sa',
    url: 'https://bugbounty.sa',
    region: 'Saudi Arabia',
    twitter: 'https://x.com/BugBountySA',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://bugbounty.sa/leaderboard',
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'CCB Belgium CVD',
    url: 'https://ccb.belgium.be/cert/vulnerability-reporting-ccb',
    region: 'Belgium',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'CERT Polska CVD',
    url: 'https://cert.pl/en/cvd/',
    region: 'Poland',
    twitter: 'https://x.com/CERT_Polska_en',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://cert.pl/en/cve/',
    category: 'Government and public-interest programs',
  },
  {
    name: 'CERT-In RVDCP',
    url: 'https://www.cert-in.org.in/RVDCP.jsp',
    region: 'India',
    twitter: 'https://x.com/IndianCERT',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.cert-in.org.in/Hallof_Fame.jsp',
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'CISA VDP Platform',
    url: 'https://www.cisa.gov/resources-tools/services/vulnerability-disclosure-policy-vdp-platform',
    region: 'USA',
    twitter: 'https://x.com/CISAgov',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'DIVD',
    url: 'https://www.divd.nl',
    region: 'Netherlands',
    twitter: 'https://x.com/DIVDnl',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'HITCON ZeroDay',
    url: 'https://zeroday.hitcon.org',
    region: 'Taiwan',
    twitter: 'https://x.com/HacksInTaiwan',
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://zeroday.hitcon.org/bug-bounty/list',
    category: 'Government and public-interest programs',
  },
  {
    name: 'Japan Vulnerability Notes (JVN)',
    url: 'https://jvn.jp/en/',
    region: 'Japan',
    twitter: 'https://x.com/jpcert_en',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://jvn.jp/en/nav/',
    category: 'Government and public-interest programs',
  },
  {
    name: 'KISA KNVD',
    url: 'https://knvd.krcert.or.kr',
    region: 'South Korea',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'NCIIPC RVDP',
    url: 'https://nciipc.gov.in/RVDP.html',
    region: 'India',
    twitter: 'https://x.com/NCIIPC',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'NCSA Bug Bounty Programme',
    url: 'https://hub.ncsa.gov.mv/resources/bug-bounty-program',
    region: 'Maldives',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://hub.ncsa.gov.mv/bug-bounty/hall-of-fame',
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'NCSC-FI CVD',
    url: 'https://www.kyberturvallisuuskeskus.fi/en/report',
    region: 'Finland',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'NCSC-NL CVD',
    url: 'https://www.ncsc.nl/contact/kwetsbaarheid-melden',
    region: 'Netherlands',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'NKSC Lithuania CVD',
    url: 'https://www.nksc.lt/pranesti-spraga.html',
    region: 'Lithuania',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'Open Bug Bounty',
    url: 'https://openbugbounty.org',
    region: 'Global',
    twitter: 'https://x.com/openbugbounty',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://openbugbounty.org/bugbounty-list/',
    category: 'Government and public-interest programs',
  },
  {
    name: 'Qatar Bug Bounty',
    url: 'https://bugbounty.qa',
    region: 'Qatar',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'Singapore GovTech VDP',
    url: 'https://www.tech.gov.sg/report-vulnerability/',
    region: 'Singapore',
    twitter: 'https://x.com/GovTechSG',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'Swiss NCSC Bug Bounty',
    url: 'https://www.ncsc.admin.ch',
    region: 'Switzerland',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'Taiwan Vulnerability Note (TVN)',
    url: 'https://www.twcert.org.tw/en/np-138-2.html',
    region: 'Taiwan',
    twitter: 'https://x.com/TWCERTCC',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://www.twcert.org.tw/en/lp-139-2.html',
    category: 'Government and public-interest programs',
  },
  {
    name: 'UAE National Bug Bounty',
    url: 'https://bugbounty.ae',
    region: 'United Arab Emirates',
    twitter: null,
    programTypes: 'Private',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'UK NCSC VDP',
    url: 'https://www.ncsc.gov.uk',
    region: 'UK',
    twitter: 'https://x.com/NCSC',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Government and public-interest programs',
  },
  {
    name: 'AuditOne',
    url: 'https://auditone.io',
    region: 'Europe',
    twitter: 'https://x.com/AuditOne_io',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.auditone.io/bounty-activity',
    publicProgramsUrl: 'https://www.auditone.io/bug-bounty',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'BugRap',
    url: 'https://bugrap.io',
    region: null,
    twitter: 'https://x.com/BugRap_Team',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://bugrap.io/whiteHats',
    publicProgramsUrl: 'https://bugrap.io/bounties',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Cantina',
    url: 'https://cantina.xyz',
    region: 'USA',
    twitter: 'https://x.com/Cantinaxyz',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://cantina.xyz/leaderboard',
    publicProgramsUrl: 'https://cantina.xyz/competitions',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'CertiK Bug Bounty',
    url: 'https://certik.com',
    region: 'USA',
    twitter: 'https://x.com/CertiK',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.certik.com/products/bug-bounty',
    publicProgramsUrl: null,
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Certora Contests',
    url: 'https://www.certora.com/contests',
    region: 'Global',
    twitter: 'https://x.com/certora',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.certora.com/leaderboard',
    publicProgramsUrl: 'https://www.certora.com/contests',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Code4rena',
    url: 'https://code4rena.com',
    region: null,
    twitter: 'https://x.com/code4rena',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://code4rena.com/leaderboard',
    publicProgramsUrl: 'https://code4rena.com/contests',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'CodeHawks',
    url: 'https://codehawks.cyfrin.io',
    region: 'USA',
    twitter: 'https://x.com/CodeHawks',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://codehawks.cyfrin.io/leaderboard',
    publicProgramsUrl: 'https://codehawks.cyfrin.io/contests',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'HackenProof',
    url: 'https://hackenproof.com',
    region: 'Estonia',
    twitter: 'https://x.com/HackenProof',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://hackenproof.com/leaderboard',
    publicProgramsUrl: 'https://hackenproof.com/programs',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Hashlock',
    url: 'https://hashlock.com',
    region: 'Australia',
    twitter: 'https://x.com/HashLockAudit',
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://hashlock.com/bug-bounty',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Hats',
    url: 'https://hats.finance',
    region: null,
    twitter: 'https://x.com/HatsFinance',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Immunefi',
    url: 'https://immunefi.com',
    region: null,
    twitter: 'https://x.com/immunefi',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://immunefi.com/leaderboard/',
    publicProgramsUrl: 'https://immunefi.com/explore/',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'OpenBounty (Shentu)',
    url: 'https://openbounty.shentu.org',
    region: null,
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://openbounty.shentu.org/leaderboard',
    publicProgramsUrl: 'https://openbounty.shentu.org/allBounties',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Remedy',
    url: 'https://r.xyz',
    region: 'Global',
    twitter: 'https://x.com/xyz_remedy',
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://hunt.r.xyz',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Secure3',
    url: 'https://secure3.io',
    region: 'USA',
    twitter: 'https://x.com/Secure3io',
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Sherlock',
    url: 'https://sherlock.xyz',
    region: 'Global',
    twitter: 'https://x.com/sherlockdefi',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://app.sherlock.xyz/audits/leaderboard',
    publicProgramsUrl: 'https://app.sherlock.xyz/audits/contests',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'SlowMist',
    url: 'https://slowmist.com',
    region: 'China',
    twitter: 'https://x.com/SlowMist_Team',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://slowmist.io/bug-bounty.html',
    category: 'Web3 and smart-contract platforms',
  },
  {
    name: 'Gray Swan Arena',
    url: 'https://app.grayswan.ai/arena',
    region: 'USA',
    twitter: 'https://x.com/GraySwanAI',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://app.grayswan.ai/arena/leaderboard/global',
    publicProgramsUrl: 'https://app.grayswan.ai/arena',
    category: 'AI and LLM security platforms',
  },
  {
    name: 'HackAPrompt',
    url: 'https://www.hackaprompt.com',
    region: 'USA',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.hackaprompt.com/leaderboard',
    publicProgramsUrl: null,
    category: 'AI and LLM security platforms',
  },
  {
    name: 'Huntr',
    url: 'https://huntr.com',
    region: 'UK',
    twitter: 'https://x.com/huntrdev',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://huntr.com/leaderboard',
    publicProgramsUrl: 'https://huntr.com/bounties/hacktivity',
    category: 'AI and LLM security platforms',
  },
  {
    name: 'ødin',
    url: 'https://0din.ai',
    region: 'USA',
    twitter: 'https://x.com/0dinai',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://0din.ai/leaderboard',
    publicProgramsUrl: 'https://0din.ai/scope',
    category: 'AI and LLM security platforms',
  },
  {
    name: 'SSD Secure Disclosure',
    url: 'https://ssd-disclosure.com',
    region: 'Israel',
    twitter: 'https://x.com/SecuriTeam_SSD',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Vulnerability acquisition and brokered disclosure',
  },
  {
    name: 'Zero Day Initiative',
    url: 'https://zerodayinitiative.com',
    region: 'USA',
    twitter: 'https://x.com/thezdi',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://zerodayinitiative.com/advisories/published/',
    publicProgramsUrl: null,
    category: 'Vulnerability acquisition and brokered disclosure',
  },
  {
    name: 'IssueHunt',
    url: 'https://issuehunt.io',
    region: 'Japan',
    twitter: 'https://x.com/IssueHunt',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://issuehunt.io/programs',
    category: 'Ecosystem-specific platforms',
  },
  {
    name: 'Patchstack',
    url: 'https://patchstack.com',
    region: 'Estonia',
    twitter: 'https://x.com/paborza',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://patchstack.com/database/leaderboard',
    publicProgramsUrl: 'https://patchstack.com/database/vdp',
    category: 'Ecosystem-specific platforms',
  },
  {
    name: 'Wordfence Bug Bounty',
    url: 'https://www.wordfence.com/threat-intel/bug-bounty-program/',
    region: 'USA',
    twitter: 'https://x.com/wordfence',
    programTypes: 'Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'Ecosystem-specific platforms',
  },
  {
    name: '360 SRC',
    url: 'https://src.360.net',
    region: 'China',
    twitter: null,
    programTypes: 'Public + Private',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BBHunt Japan',
    url: 'https://bbhunt.jp',
    region: 'Japan',
    twitter: 'https://x.com/bbhuntjapan',
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BI.ZONE Bug Bounty',
    url: 'https://bugbounty.bi.zone',
    region: 'Russia',
    twitter: 'https://x.com/bizone',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://bugbounty.bi.zone/top-hackers',
    publicProgramsUrl: 'https://bugbounty.bi.zone/companies',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BountyTeam',
    url: 'https://www.bountyteam.com',
    region: 'China',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.bountyteam.com/leader-board',
    publicProgramsUrl: 'https://www.bountyteam.com/bug-bounty-list',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bug Bounty Switzerland',
    url: 'https://bugbounty.ch',
    region: 'Switzerland',
    twitter: 'https://x.com/bugbounty_ch',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://www.bugbounty.ch/en/programs/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bug Hunt',
    url: 'https://bughunt.com.br',
    region: 'Brazil',
    twitter: 'https://x.com/bughuntoficial',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bug Zero',
    url: 'https://bugzero.io',
    region: 'Sri Lanka',
    twitter: 'https://x.com/BugZero_io',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://bugzero.io/leaderboard',
    publicProgramsUrl: 'https://bugzero.io/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BugBank',
    url: 'https://www.bugbank.cn',
    region: 'China',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.bugbank.cn/ranks.html',
    publicProgramsUrl: 'https://www.bugbank.cn/task/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bugbase',
    url: 'https://bugbase.ai',
    region: 'India',
    twitter: 'https://x.com/bugbase',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://bugbase.ai/dashboard/leaderboard',
    publicProgramsUrl: 'https://bugbase.ai/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bugbop',
    url: 'https://bugbop.com',
    region: 'Australia',
    twitter: 'https://x.com/BugbopApp',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://bugbop.com/public-programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BugBounter',
    url: 'https://bugbounter.com',
    region: 'US & Estonia & Turkey',
    twitter: 'https://x.com/bugbounterr',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://app.bugbounter.com/public-top-bounters',
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BugBounty.am',
    url: 'https://bugbounty.am',
    region: 'Armenia',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'bugbounty.jp',
    url: 'https://bugbounty.jp',
    region: 'Japan',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: 'https://bugbounty.jp/en/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BugBounty.ru',
    url: 'https://bugbounty.ru',
    region: 'Russia',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: 'https://bugbounty.ru/app/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bugcrowd',
    url: 'https://bugcrowd.com',
    region: 'USA',
    twitter: 'https://x.com/bugcrowd',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://bugcrowd.com/leaderboard',
    publicProgramsUrl: 'https://bugcrowd.com/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Buglab',
    url: 'https://buglab.io',
    region: 'Singapore',
    twitter: 'https://x.com/joinbuglab',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bugloud',
    url: 'https://bugloud.com',
    region: 'United Arab Emirates',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://bugloud.com/leaderboard',
    publicProgramsUrl: 'https://bugloud.com/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'BugRakshak',
    url: 'https://www.bugrakshak.com',
    region: 'India',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.bugrakshak.com/platform/leaderboard',
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'bugsbounty.io',
    url: 'https://bugsbounty.com',
    region: 'England',
    twitter: 'https://x.com/bugsbounty_com',
    programTypes: 'Private',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Bugv',
    url: 'https://bugv.io',
    region: 'Nepal',
    twitter: 'https://x.com/bugvsecurity',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Butian',
    url: 'https://butian.net',
    region: 'China',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.butian.net/Rank/whitehat',
    publicProgramsUrl: 'https://www.butian.net/Reward/plan/2',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Capture The Bug',
    url: 'https://capturethebug.xyz',
    region: 'New Zealand',
    twitter: 'https://x.com/Capturethebugs',
    programTypes: 'Private',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Cobalt',
    url: 'https://cobalt.io',
    region: 'USA',
    twitter: 'https://x.com/cobalt_io',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://app.us.cobalt.io/pentesters',
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Com Olho',
    url: 'https://comolho.com',
    region: 'India',
    twitter: 'https://x.com/com_olho',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://cyber.comolho.com/researcher-community/',
    publicProgramsUrl: 'https://cyber.comolho.com/programs/bug-bounty/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Compass Security',
    url: 'https://compass-security.com',
    region: 'Switzerland',
    twitter: 'https://x.com/compasssecurity',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://bugbounty.compass-security.com/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Crowdswarm',
    url: 'https://crowdswarm.io',
    region: 'United Arab Emirates',
    twitter: 'https://x.com/Crowdswarm1',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Cyber Army Indonesia',
    url: 'https://www.cyberarmy.asia',
    region: 'Indonesia',
    twitter: 'https://x.com/cyberarmyid',
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Cyber3ra',
    url: 'https://cyber3ra.com',
    region: 'India',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Cyberbay',
    url: 'https://cyberbay.tech',
    region: 'Hong Kong',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'CyberTalents',
    url: 'https://cybertalents.com',
    region: 'Middle East',
    twitter: 'https://x.com/CyberTalents',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://cybertalents.com/worldrank',
    publicProgramsUrl: 'https://cybertalents.com/competitions',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Cyscope',
    url: 'https://cyscope.io',
    region: 'Switzerland & Latam',
    twitter: 'https://x.com/cy_scope',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Detectify',
    url: 'https://detectify.com',
    region: 'Sweden',
    twitter: 'https://x.com/detectify',
    programTypes: 'Crowdsource (ASM)',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Dvuln',
    url: 'https://dvuln.com',
    region: 'Australia',
    twitter: 'https://x.com/d_vuln',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Federacy',
    url: 'https://federacy.com',
    region: 'USA',
    twitter: 'https://x.com/_federacy',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Find The Gap',
    url: 'https://findthegap.co.kr/en',
    region: 'South Korea',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Findbug',
    url: 'https://findbug.io',
    region: 'Kosovo',
    twitter: 'https://x.com/Findbugks',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Genbounty',
    url: 'https://genbounty.com/',
    region: 'UK',
    twitter: 'https://x.com/genbounty',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://genbounty.com/teams',
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Gerobug',
    url: 'https://gerobug.gerosecurity.com',
    region: 'Indonesia',
    twitter: null,
    programTypes: 'Self-hosted',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://gerobug.gerosecurity.com/programs/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'GObugfree',
    url: 'https://gobugfree.com',
    region: 'Switzerland',
    twitter: 'https://x.com/gobugfree',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://gobugfree.com/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'HackerOne',
    url: 'https://hackerone.com',
    region: 'USA',
    twitter: 'https://x.com/hacker0x01',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://hackerone.com/leaderboard',
    publicProgramsUrl: 'https://hackerone.com/directory/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Hackr.fi',
    url: 'https://www.hackr.fi',
    region: 'Finland',
    twitter: 'https://x.com/hackrfi',
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://www.hackr.fi/en/programs.html',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Hackrate',
    url: 'https://hckrt.com',
    region: 'Hungary',
    twitter: 'https://x.com/hackrate',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://hckrt.com/Catalog',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'HACKTIFY',
    url: 'https://hacktify.eu',
    region: 'Central and Eastern Europe',
    twitter: 'https://x.com/HACKTIFY_',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://hacktify.eu/en/leaderboard/',
    publicProgramsUrl: 'https://hacktify.eu/en/public-programs/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'HuntBug',
    url: 'https://huntbug.com',
    region: 'USA',
    twitter: 'https://x.com/officialhuntbug',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://huntbug.com/leaderboard',
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'HuntersPay',
    url: 'https://www.hunterspay.com.br',
    region: 'Brazil',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Huoxian',
    url: 'https://www.huoxian.cn',
    region: 'China',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.huoxian.cn/community',
    publicProgramsUrl: 'https://www.huoxian.cn/project',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Inspectiv',
    url: 'https://inspectiv.com',
    region: 'USA',
    twitter: 'https://x.com/inspectiv',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Intigriti',
    url: 'https://intigriti.com',
    region: 'Belgium',
    twitter: 'https://x.com/intigriti',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://intigriti.com/leaderboard',
    publicProgramsUrl: 'https://intigriti.com/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Kolahsefid',
    url: 'https://www.kolahsefid.org',
    region: 'Iran',
    twitter: 'https://x.com/Kolaahsefid',
    programTypes: 'Private + Public',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Nordic Defender',
    url: 'https://nordicdefender.com',
    region: 'Sweden',
    twitter: 'https://x.com/nordicdefender',
    programTypes: 'Private',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'PatchDay',
    url: 'https://patchday.io',
    region: 'South Korea',
    twitter: 'https://x.com/patchday_io',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Ravro',
    url: 'https://ravro.ir',
    region: 'Iran',
    twitter: 'https://x.com/Ravro_ir',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://ravro.ir/reports',
    publicProgramsUrl: 'https://ravro.ir/companies',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'RedStorm',
    url: 'https://redstorm.io',
    region: 'Indonesia',
    twitter: 'https://x.com/redstorm_io',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://redstorm.io/program',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'safehats',
    url: 'https://safehats.com',
    region: 'India',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Safevuln',
    url: 'https://safevuln.com',
    region: 'Vietnam',
    twitter: null,
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://safevuln.com/leaderboard',
    publicProgramsUrl: 'https://safevuln.com/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Secuna',
    url: 'https://secuna.io',
    region: 'Philippines',
    twitter: 'https://x.com/SecunaSecurity',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: 'https://platform.secuna.io/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Secur0',
    url: 'https://secur0.com',
    region: 'Europe & Latam',
    twitter: 'https://x.com/Secur00',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://app.secur0.com/leaderboards',
    publicProgramsUrl: 'https://app.secur0.com/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Standoff 365 Bug Bounty',
    url: 'https://bugbounty.standoff365.com',
    region: 'Russia',
    twitter: 'https://x.com/standoff365',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://standoff365.com/en-US/ratings/',
    publicProgramsUrl: 'https://bugbounty.standoff365.com/en-US/',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Swarmnetics',
    url: 'https://swarmnetics.com',
    region: 'Singapore',
    twitter: 'https://x.com/swarmnetics',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Synack',
    url: 'https://synack.com',
    region: 'USA',
    twitter: 'https://x.com/synack',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Teklabspace',
    url: 'https://teklabspace.com',
    region: 'Nigeria',
    twitter: 'https://x.com/teklabspace',
    programTypes: 'Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Testbirds',
    url: 'https://testbirds.com',
    region: 'Germany',
    twitter: 'https://x.com/Testbirds',
    programTypes: 'QA + Bug Bounty',
    hasLeaderboard: 'No',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Topcoder',
    url: 'https://topcoder.com',
    region: 'USA',
    twitter: 'https://x.com/topcoder',
    programTypes: 'Dev + Bug Bounty',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://www.topcoder.com/community/statistics',
    publicProgramsUrl: 'https://www.topcoder.com/challenges',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'TrustLine',
    url: 'https://www.trustline.sa',
    region: 'Saudi Arabia',
    twitter: 'https://x.com/trustlineSec',
    programTypes: 'Private + Public',
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'TumarOne',
    url: 'https://tumar.one',
    region: 'Kazakhstan',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://tumar.one/leaderboard',
    publicProgramsUrl: 'https://tumar.one/#for-bug-hunters',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'UzHunter',
    url: 'https://uzhunter.com',
    region: 'Uzbekistan',
    twitter: null,
    programTypes: null,
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Vulbox',
    url: 'https://vulbox.com',
    region: 'China',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://vulbox.com/top/season',
    publicProgramsUrl: 'https://vulbox.com/projects/list',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Vulnerability Lab',
    url: 'https://vulnerability-lab.com',
    region: 'Germany',
    twitter: null,
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://vulnerability-lab.com/hacktivity.php',
    publicProgramsUrl: 'https://www.vulnerability-lab.com/list-of-bug-bounty-programs.php',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Vulnscope',
    url: 'https://vulnscope.com',
    region: 'Chile',
    twitter: 'https://x.com/vulnscope',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://vulnscope.com/hacker-ranking',
    publicProgramsUrl: 'https://vulnscope.com/programas',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'WhiteHub',
    url: 'https://whitehub.net',
    region: 'Vietnam',
    twitter: 'https://x.com/CyStackSecurity',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://whitehub.net/leaderboard',
    publicProgramsUrl: 'https://whitehub.net/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'YesWeHack',
    url: 'https://yeswehack.com',
    region: 'France',
    twitter: 'https://x.com/yeswehack',
    programTypes: 'Private + Public',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://yeswehack.com/ranking',
    publicProgramsUrl: 'https://yeswehack.com/programs',
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Yogosha',
    url: 'https://yogosha.com',
    region: 'France',
    twitter: 'https://x.com/yogoshaofficial',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: 'https://yogosha.com/hackers/leaderboard/',
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'Zerocopter',
    url: 'https://zerocopter.com',
    region: 'Netherlands',
    twitter: 'https://x.com/zerocopter',
    programTypes: 'Private',
    hasLeaderboard: 'Yes',
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
  {
    name: 'ZeroDay Test',
    url: 'https://zerodaytest.com',
    region: 'Bangladesh',
    twitter: 'https://x.com/Zer0day_t3st',
    programTypes: null,
    hasLeaderboard: null,
    leaderboardUrl: null,
    publicProgramsUrl: null,
    category: 'General crowdsourced platforms',
  },
];

export default platforms;
