// All category names, ordering, and years are sourced directly from
// OWASP's own published documents (owasp.org/Top10, owasp.org/API-Security)
// — descriptions below are written in our own words, not copied from
// OWASP's text. Technique lists are well-known, named attack techniques
// commonly associated with each category, for educational orientation —
// not exploit instructions.
//
// THEMES exist so the wheel's color-coding means something consistent
// across every edition and year, instead of an arbitrary rainbow: the same
// four colors always mean the same broad category of failure, no matter
// which edition you're looking at.
export const THEMES = {
  access: {label: 'Access & Identity', color: 'red'},
  data: {label: 'Data & Crypto', color: 'blue'},
  injection: {label: 'Injection & Input', color: 'amber'},
  design: {label: 'Design, Config & Ops', color: 'green'},
};

export const EDITIONS = {
  web2017: {
    track: 'web',
    year: 2017,
    label: 'OWASP Top 10',
    sourceUrl: 'https://owasp.org/www-project-top-ten/2017/',
    categories: [
      {
        code: 'A1',
        name: 'Injection',
        theme: 'injection',
        description: 'Untrusted input gets interpreted as commands or queries by an interpreter, letting an attacker run their own logic instead of the app\'s.',
        techniques: ['SQL Injection', 'OS Command Injection', 'LDAP Injection', 'XPath Injection'],
      },
      {
        code: 'A2',
        name: 'Broken Authentication',
        theme: 'access',
        description: 'Flaws in login, session, or credential handling let attackers assume other users\' identities.',
        techniques: ['Credential Stuffing', 'Session Fixation', 'Weak Password Recovery', 'Session ID in URL'],
      },
      {
        code: 'A3',
        name: 'Sensitive Data Exposure',
        theme: 'data',
        description: 'Sensitive data (financial, health, credentials) isn\'t adequately protected at rest or in transit.',
        techniques: ['Cleartext Storage', 'Weak Encryption Algorithms', 'Missing TLS', 'Exposed Backup Files'],
      },
      {
        code: 'A4',
        name: 'XML External Entities (XXE)',
        theme: 'data',
        description: 'Poorly configured XML parsers process external entity references, leaking files or enabling further attacks.',
        techniques: ['XXE File Disclosure', 'XXE-based SSRF', 'Billion Laughs (XML Bomb)', 'Blind XXE via OOB Channel'],
      },
      {
        code: 'A5',
        name: 'Broken Access Control',
        theme: 'access',
        description: 'Restrictions on what authenticated users can do aren\'t properly enforced server-side.',
        techniques: ['IDOR', 'Forced Browsing', 'Privilege Escalation', 'CORS Misconfiguration'],
      },
      {
        code: 'A6',
        name: 'Security Misconfiguration',
        theme: 'design',
        description: 'Insecure default settings, incomplete configurations, or unnecessary features left enabled.',
        techniques: ['Default Credentials', 'Verbose Error Messages', 'Unpatched Software', 'Open Cloud Storage Buckets'],
      },
      {
        code: 'A7',
        name: 'Cross-Site Scripting (XSS)',
        theme: 'injection',
        description: 'Untrusted data is rendered in a browser without proper escaping, letting attacker scripts run in a victim\'s session.',
        techniques: ['Reflected XSS', 'Stored XSS', 'DOM-based XSS', 'Mutation XSS'],
      },
      {
        code: 'A8',
        name: 'Insecure Deserialization',
        theme: 'injection',
        description: 'Untrusted data is deserialized into objects, which can lead to remote code execution or logic tampering.',
        techniques: ['Java Deserialization RCE', 'PHP Object Injection', 'Python Pickle Exploitation'],
      },
      {
        code: 'A9',
        name: 'Using Components with Known Vulnerabilities',
        theme: 'design',
        description: 'Libraries, frameworks, and other components are used with known, publicly disclosed vulnerabilities.',
        techniques: ['Known-CVE Library Exploitation', 'Unpatched CMS Plugins', 'Outdated Framework Exploits'],
      },
      {
        code: 'A10',
        name: 'Insufficient Logging & Monitoring',
        theme: 'design',
        description: 'Breaches go undetected for long periods because activity isn\'t logged or alerted on.',
        techniques: ['Silent Brute-Force', 'Undetected Data Exfiltration', 'Missing Alerting on Auth Failures'],
      },
    ],
  },

  web2021: {
    track: 'web',
    year: 2021,
    label: 'OWASP Top 10',
    sourceUrl: 'https://owasp.org/Top10/',
    categories: [
      {
        code: 'A01',
        name: 'Broken Access Control',
        theme: 'access',
        changeNote: 'Moved up from #5 in 2017 to #1 — the single most common finding across OWASP\'s underlying dataset.',
        description: 'Restrictions on what authenticated users can do aren\'t properly enforced server-side.',
        techniques: ['IDOR', 'Privilege Escalation', 'CORS Misconfiguration', 'Forced Browsing', 'JWT Tampering'],
      },
      {
        code: 'A02',
        name: 'Cryptographic Failures',
        theme: 'data',
        changeNote: 'Renamed and broadened from "Sensitive Data Exposure" — the root cause (crypto misuse), not just the symptom.',
        description: 'Sensitive data is exposed due to weak, missing, or misused cryptography.',
        techniques: ['Weak Password Hashing (MD5/SHA1)', 'Hardcoded Keys', 'Missing Encryption at Rest', 'Downgrade Attacks'],
      },
      {
        code: 'A03',
        name: 'Injection',
        theme: 'injection',
        changeNote: 'XSS was folded into this category, having previously been its own entry.',
        description: 'Untrusted input gets interpreted as commands or queries by an interpreter.',
        techniques: ['SQL Injection', 'Command Injection', 'NoSQL Injection', 'Cross-Site Scripting'],
      },
      {
        code: 'A04',
        name: 'Insecure Design',
        theme: 'design',
        changeNote: 'New category — flaws baked into the architecture itself, not just implementation bugs.',
        description: 'Missing or ineffective security controls at the design stage, before a single line of code is written.',
        techniques: ['Missing Rate Limiting by Design', 'Trusting Client-Side Validation', 'Flawed Business Logic'],
      },
      {
        code: 'A05',
        name: 'Security Misconfiguration',
        theme: 'design',
        description: 'Insecure default settings, incomplete configurations, or unnecessary features left enabled.',
        techniques: ['Default Credentials', 'Verbose Errors', 'Unnecessary Features Enabled', 'Missing Security Headers'],
      },
      {
        code: 'A06',
        name: 'Vulnerable and Outdated Components',
        theme: 'design',
        description: 'Libraries, frameworks, and other components are used with known vulnerabilities or without support.',
        techniques: ['Known-CVE Library Exploitation', 'Unsupported Software', 'Dependency Confusion'],
      },
      {
        code: 'A07',
        name: 'Identification and Authentication Failures',
        theme: 'access',
        changeNote: 'Renamed from "Broken Authentication" to include identity management more broadly.',
        description: 'Flaws in login, session, or identity handling let attackers assume other users\' identities.',
        techniques: ['Credential Stuffing', 'Brute Force', 'Session Fixation', 'Weak Session Tokens'],
      },
      {
        code: 'A08',
        name: 'Software and Data Integrity Failures',
        theme: 'injection',
        changeNote: 'New category, absorbing Insecure Deserialization and adding CI/CD and update-integrity risks.',
        description: 'Code or infrastructure that doesn\'t verify integrity, allowing tampering with updates, pipelines, or serialized data.',
        techniques: ['Insecure Deserialization', 'Unsigned Software Updates', 'CI/CD Pipeline Poisoning'],
      },
      {
        code: 'A09',
        name: 'Security Logging and Monitoring Failures',
        theme: 'design',
        description: 'Breaches go undetected for long periods because activity isn\'t logged or alerted on.',
        techniques: ['Undetected Breaches', 'Missing Audit Trails', 'Log Injection'],
      },
      {
        code: 'A10',
        name: 'Server-Side Request Forgery (SSRF)',
        theme: 'injection',
        changeNote: 'New standalone category — previously a niche entry, promoted due to rising real-world impact.',
        description: 'An application fetches a remote resource without validating the destination, letting an attacker reach internal systems.',
        techniques: ['Cloud Metadata Endpoint Access', 'Internal Port Scanning via SSRF', 'Blind SSRF'],
      },
    ],
  },

  web2025: {
    track: 'web',
    year: 2025,
    label: 'OWASP Top 10',
    sourceUrl: 'https://owasp.org/Top10/2025/',
    categories: [
      {
        code: 'A01',
        name: 'Broken Access Control',
        theme: 'access',
        changeNote: 'Stays #1, and now absorbs SSRF (2021\'s A10), reflecting that SSRF is fundamentally an access-control failure.',
        description: 'Restrictions on what authenticated users can do aren\'t properly enforced server-side.',
        techniques: ['IDOR', 'Privilege Escalation', 'Server-Side Request Forgery', 'CORS Misconfiguration', 'JWT Tampering'],
      },
      {
        code: 'A02',
        name: 'Security Misconfiguration',
        theme: 'design',
        changeNote: 'Climbed from #5 in 2021 to #2.',
        description: 'Insecure default settings, incomplete configurations, or unnecessary features left enabled.',
        techniques: ['Default Credentials', 'Exposed Debug Endpoints', 'Missing Security Headers', 'Misconfigured Cloud Storage'],
      },
      {
        code: 'A03',
        name: 'Software Supply Chain Failures',
        theme: 'design',
        changeNote: 'New category, broadening 2021\'s "Vulnerable and Outdated Components" beyond known-CVE libraries to the entire dependency chain.',
        description: 'Trust placed in third-party dependencies, build pipelines, and open-source packages is exploited to inject malicious code.',
        techniques: ['Dependency Confusion', 'Malicious npm/PyPI Packages', 'Compromised CI/CD Pipelines', 'Typosquatting'],
      },
      {
        code: 'A04',
        name: 'Cryptographic Failures',
        theme: 'data',
        description: 'Sensitive data is exposed due to weak, missing, or misused cryptography.',
        techniques: ['Weak Password Hashing', 'Hardcoded Secrets', 'Missing Encryption at Rest', 'Downgrade Attacks'],
      },
      {
        code: 'A05',
        name: 'Injection',
        theme: 'injection',
        description: 'Untrusted input gets interpreted as commands or queries by an interpreter.',
        techniques: ['SQL Injection', 'Command Injection', 'Cross-Site Scripting', 'NoSQL Injection'],
      },
      {
        code: 'A06',
        name: 'Insecure Design',
        theme: 'design',
        description: 'Missing or ineffective security controls at the design stage, before a single line of code is written.',
        techniques: ['Flawed Business Logic', 'Missing Threat Modeling', 'Trusting Client-Side Validation'],
      },
      {
        code: 'A07',
        name: 'Authentication Failures',
        theme: 'access',
        changeNote: 'Shortened name from 2021\'s "Identification and Authentication Failures."',
        description: 'Flaws in login or identity handling let attackers assume other users\' identities.',
        techniques: ['Credential Stuffing', 'Brute Force', 'MFA Bypass', 'Session Fixation'],
      },
      {
        code: 'A08',
        name: 'Software or Data Integrity Failures',
        theme: 'injection',
        description: 'Code or data that doesn\'t verify integrity, allowing tampering with updates or serialized objects.',
        techniques: ['Insecure Deserialization', 'Unsigned Updates', 'Prototype Pollution'],
      },
      {
        code: 'A09',
        name: 'Security Logging and Alerting Failures',
        theme: 'design',
        changeNote: 'Renamed from "...Monitoring Failures" to stress that unactioned logs have little value.',
        description: 'Breaches go undetected because activity isn\'t logged, or logs exist but nobody acts on them.',
        techniques: ['Undetected Breaches', 'Alert Fatigue', 'Missing Audit Trails'],
      },
      {
        code: 'A10',
        name: 'Mishandling of Exceptional Conditions',
        theme: 'design',
        changeNote: 'Brand-new category — poor error/exception handling as its own top-level risk for the first time.',
        description: 'Errors, edge cases, and unexpected states aren\'t handled safely, leaking information or leaving the app in an insecure state.',
        techniques: ['Verbose Stack Traces', 'Fail-Open Error Handling', 'Unhandled Edge Cases Enabling Bypass'],
      },
    ],
  },

  api2019: {
    track: 'api',
    year: 2019,
    label: 'API Security Top 10',
    sourceUrl: 'https://owasp.org/www-project-api-security/',
    categories: [
      {
        code: 'API1',
        name: 'Broken Object Level Authorization',
        theme: 'access',
        description: 'An API endpoint doesn\'t verify the caller is allowed to access the specific object ID requested.',
        techniques: ['IDOR via API', 'Object ID Enumeration', 'Horizontal Privilege Escalation'],
      },
      {
        code: 'API2',
        name: 'Broken User Authentication',
        theme: 'access',
        description: 'Weak or missing authentication mechanisms let attackers assume other identities.',
        techniques: ['Credential Stuffing', 'Weak API Keys', 'JWT "none" Algorithm Attack', 'Token Replay'],
      },
      {
        code: 'API3',
        name: 'Excessive Data Exposure',
        theme: 'data',
        description: 'APIs return more data than the client needs, relying on the frontend to filter it.',
        techniques: ['Over-fetching in Responses', 'Unfiltered Sensitive Fields', 'Verbose Error Bodies'],
      },
      {
        code: 'API4',
        name: 'Lack of Resources & Rate Limiting',
        theme: 'design',
        description: 'No limits on request frequency or payload size, enabling abuse or denial of service.',
        techniques: ['API Flooding', 'Brute Force via Unlimited Requests', 'Resource Exhaustion'],
      },
      {
        code: 'API5',
        name: 'Broken Function Level Authorization',
        theme: 'access',
        description: 'An API doesn\'t verify the caller\'s role before executing privileged operations.',
        techniques: ['Admin Endpoint Access as Regular User', 'Vertical Privilege Escalation'],
      },
      {
        code: 'API6',
        name: 'Mass Assignment',
        theme: 'injection',
        description: 'Client input is bound directly to internal objects, letting attackers set fields they shouldn\'t control.',
        techniques: ['Overposting Hidden Fields', 'Role Field Injection via Request Body'],
      },
      {
        code: 'API7',
        name: 'Security Misconfiguration',
        theme: 'design',
        description: 'Insecure default settings or unnecessary features left enabled on API infrastructure.',
        techniques: ['Verbose CORS', 'Default Configs', 'Unnecessary HTTP Methods Enabled'],
      },
      {
        code: 'API8',
        name: 'Injection',
        theme: 'injection',
        description: 'Untrusted input passed to an API parameter gets interpreted as a command or query.',
        techniques: ['SQL Injection via API Params', 'Command Injection', 'NoSQL Injection'],
      },
      {
        code: 'API9',
        name: 'Improper Assets Management',
        theme: 'design',
        description: 'Old, undocumented, or forgotten API versions remain live and unmonitored.',
        techniques: ['Zombie/Shadow API Versions', 'Undocumented Endpoints', 'Deprecated Endpoint Exposure'],
      },
      {
        code: 'API10',
        name: 'Insufficient Logging & Monitoring',
        theme: 'design',
        description: 'API abuse goes undetected because activity isn\'t logged or alerted on.',
        techniques: ['Undetected API Abuse', 'Missing Rate-Limit Alerts'],
      },
    ],
  },

  api2023: {
    track: 'api',
    year: 2023,
    label: 'API Security Top 10',
    sourceUrl: 'https://owasp.org/API-Security/editions/2023/en/0x00-header/',
    categories: [
      {
        code: 'API1',
        name: 'Broken Object Level Authorization',
        theme: 'access',
        description: 'An API endpoint doesn\'t verify the caller is allowed to access the specific object ID requested. Still the most common API finding.',
        techniques: ['IDOR via API', 'Object ID Enumeration', 'Horizontal Privilege Escalation'],
      },
      {
        code: 'API2',
        name: 'Broken Authentication',
        theme: 'access',
        changeNote: 'Shortened name from "Broken User Authentication."',
        description: 'Weak or missing authentication mechanisms let attackers assume other identities.',
        techniques: ['Credential Stuffing', 'JWT "none" Algorithm Attack', 'Token Replay', 'Weak API Keys'],
      },
      {
        code: 'API3',
        name: 'Broken Object Property Level Authorization',
        theme: 'data',
        changeNote: 'Merges 2019\'s "Excessive Data Exposure" and "Mass Assignment" into one root-cause category.',
        description: 'Authorization isn\'t checked at the level of individual object properties, letting attackers read or write fields they shouldn\'t.',
        techniques: ['Overposting Hidden Fields', 'Sensitive Property Exposure', 'Mass Assignment'],
      },
      {
        code: 'API4',
        name: 'Unrestricted Resource Consumption',
        theme: 'design',
        changeNote: 'Broadened from "Lack of Resources & Rate Limiting" to cover more resource types.',
        description: 'No limits on requests, payload size, or resource-intensive operations, enabling abuse or denial of service.',
        techniques: ['API Flooding', 'Large Payload DoS', 'Unbounded Pagination Abuse'],
      },
      {
        code: 'API5',
        name: 'Broken Function Level Authorization',
        theme: 'access',
        description: 'An API doesn\'t verify the caller\'s role before executing privileged operations.',
        techniques: ['Admin Endpoint Access as Regular User', 'Vertical Privilege Escalation'],
      },
      {
        code: 'API6',
        name: 'Unrestricted Access to Sensitive Business Flows',
        theme: 'injection',
        changeNote: 'Brand-new category, addressing automated abuse of legitimate business logic (scalping, fake accounts).',
        description: 'Legitimate business workflows are automated and abused at scale, even without a traditional technical vulnerability.',
        techniques: ['Scalping Bots', 'Automated Fake Account Creation', 'Bulk Purchasing Abuse'],
      },
      {
        code: 'API7',
        name: 'Server Side Request Forgery',
        theme: 'injection',
        changeNote: 'New standalone category for APIs, mirroring its promotion in the 2021 web Top 10.',
        description: 'An API fetches a remote resource based on user input without validating the destination.',
        techniques: ['Cloud Metadata Access via API', 'Internal Network Pivoting'],
      },
      {
        code: 'API8',
        name: 'Security Misconfiguration',
        theme: 'design',
        description: 'Insecure default settings or unnecessary features left enabled on API infrastructure.',
        techniques: ['Verbose CORS', 'Default Configs', 'Unnecessary HTTP Methods'],
      },
      {
        code: 'API9',
        name: 'Improper Inventory Management',
        theme: 'design',
        changeNote: 'Renamed from "Improper Assets Management."',
        description: 'Old, undocumented, or forgotten API versions remain live and unmonitored.',
        techniques: ['Zombie/Shadow API Versions', 'Undocumented Endpoints'],
      },
      {
        code: 'API10',
        name: 'Unsafe Consumption of APIs',
        theme: 'data',
        changeNote: 'Brand-new category — risk from trusting third-party/upstream APIs, not just your own.',
        description: 'Data or responses from third-party APIs are trusted without validation, importing their weaknesses into your system.',
        techniques: ['Trusting Third-Party Responses Blindly', 'SSRF via Chained APIs', 'Data Injection from Upstream APIs'],
      },
    ],
  },

  mobile2016: {
    track: 'mobile',
    year: 2016,
    label: 'OWASP Mobile Top 10',
    sourceUrl: 'https://owasp.github.io/www-project-mobile-top-10/2016-risks/',
    categories: [
      {
        code: 'M1',
        name: 'Improper Platform Usage',
        theme: 'design',
        description: 'A mobile OS\'s own security features (permissions, keychain, intents) are misused or bypassed instead of relied upon.',
        techniques: ['Improper Platform Usage', 'Insecure Intent Handling', 'Misused Platform Permissions'],
      },
      {
        code: 'M2',
        name: 'Insecure Data Storage',
        theme: 'data',
        description: 'Sensitive data is stored on the device in a form another app, or anyone with physical access, can read.',
        techniques: ['Insecure Data Storage', 'Unencrypted Local Database', 'Sensitive Data in Logs'],
      },
      {
        code: 'M3',
        name: 'Insecure Communication',
        theme: 'data',
        description: 'Data in transit between the app and its backend isn\'t properly protected against interception or tampering.',
        techniques: ['Insecure Communication', 'Missing Certificate Pinning', 'Cleartext Transmission'],
      },
      {
        code: 'M4',
        name: 'Insecure Authentication',
        theme: 'access',
        description: 'The app\'s login or session mechanism has weaknesses specific to a mobile context, like weak local auth or session handling.',
        techniques: ['Insecure Authentication', 'Weak Session Tokens', 'Biometric Bypass'],
      },
      {
        code: 'M5',
        name: 'Insufficient Cryptography',
        theme: 'data',
        description: 'Encryption is attempted but implemented with weak algorithms, hardcoded keys, or other flawed practices.',
        techniques: ['Weak Encryption Algorithms', 'Hardcoded Keys'],
      },
      {
        code: 'M6',
        name: 'Insecure Authorization',
        theme: 'access',
        description: 'The app fails to properly verify that a user is allowed to perform an action, distinct from whether they\'re authenticated at all.',
        techniques: ['Insecure Authorization', 'Privilege Escalation'],
      },
      {
        code: 'M7',
        name: 'Client Code Quality',
        theme: 'design',
        description: 'Ordinary coding bugs in the client (buffer overflows, format string issues) that are exploitable specifically because the code runs on a device the attacker can fully control.',
        techniques: ['Client Code Quality', 'Buffer Overflow in Native Code'],
      },
      {
        code: 'M8',
        name: 'Code Tampering',
        theme: 'design',
        description: 'An attacker modifies the app\'s binary or resources and redistributes it, since mobile apps ship as files an attacker can freely edit.',
        techniques: ['Code Tampering', 'Repackaging Attacks'],
      },
      {
        code: 'M9',
        name: 'Reverse Engineering',
        theme: 'design',
        description: 'Decompiling the app binary to recover source-level logic, embedded secrets, or algorithms it was assumed nobody could read.',
        techniques: ['Reverse Engineering', 'Binary Decompilation'],
      },
      {
        code: 'M10',
        name: 'Extraneous Functionality',
        theme: 'design',
        description: 'Hidden test code, debug backdoors, or internal-only features accidentally shipped in the production build.',
        techniques: ['Extraneous Functionality', 'Hidden Backdoor Functionality'],
      },
    ],
  },

  mobile2024: {
    track: 'mobile',
    year: 2024,
    label: 'OWASP Mobile Top 10',
    sourceUrl: 'https://owasp.github.io/www-project-mobile-top-10/2023-risks/',
    categories: [
      {
        code: 'M1',
        name: 'Improper Credential Usage',
        theme: 'access',
        changeNote: 'New #1, up from an unranked concern in 2016 — hardcoded and mishandled credentials proved the most prevalent real-world issue.',
        description: 'API keys, tokens, or other credentials are hardcoded into the app or mishandled at runtime, becoming recoverable by anyone who inspects the binary.',
        techniques: ['Improper Credential Usage', 'Hardcoded Keys'],
      },
      {
        code: 'M2',
        name: 'Inadequate Supply Chain Security',
        theme: 'design',
        changeNote: 'Brand-new category — didn\'t exist as a named risk in 2016, reflecting how many third-party SDKs a typical app now bundles.',
        description: 'Third-party SDKs and libraries compiled into the app introduce risk the app\'s own team never reviewed.',
        techniques: ['Malicious npm/PyPI Packages', 'Compromised CI/CD Pipelines'],
      },
      {
        code: 'M3',
        name: 'Insecure Authentication/Authorization',
        theme: 'access',
        changeNote: 'Merges 2016\'s separate M4 (Authentication) and M6 (Authorization) into one category.',
        description: 'Weaknesses in verifying who a user is, or what they\'re allowed to do, specific to the mobile client context.',
        techniques: ['Insecure Authentication', 'Insecure Authorization', 'Privilege Escalation'],
      },
      {
        code: 'M4',
        name: 'Insufficient Input/Output Validation',
        theme: 'injection',
        description: 'Data entering or leaving the app isn\'t validated, enabling injection-style attacks against the client itself.',
        techniques: ['Insufficient Input/Output Validation', 'Client Side Injection'],
      },
      {
        code: 'M5',
        name: 'Insecure Communication',
        theme: 'data',
        description: 'Data in transit between the app and its backend isn\'t properly protected against interception or tampering.',
        techniques: ['Insecure Communication', 'Missing Certificate Pinning'],
      },
      {
        code: 'M6',
        name: 'Inadequate Privacy Controls',
        theme: 'data',
        changeNote: 'Brand-new category, reflecting the regulatory weight now attached to how apps handle personal data.',
        description: 'The app collects, stores, or shares more personal data than it discloses to the user, or fails to honor privacy settings.',
        techniques: ['Inadequate Privacy Controls', 'Excessive Data Collection'],
      },
      {
        code: 'M7',
        name: 'Insufficient Binary Protections',
        theme: 'design',
        changeNote: 'Consolidates 2016\'s M8/M9 (Code Tampering, Reverse Engineering) into one category framed around the missing defenses.',
        description: 'The compiled app lacks defenses (obfuscation, integrity checks, anti-debugging) against tampering or reverse engineering.',
        techniques: ['Insufficient Binary Protections', 'Anti-Tampering Bypass'],
      },
      {
        code: 'M8',
        name: 'Security Misconfiguration',
        theme: 'design',
        description: 'Insecure default settings or unnecessary features left enabled in the shipped app.',
        techniques: ['Default Credentials', 'Verbose Error Messages'],
      },
      {
        code: 'M9',
        name: 'Insecure Data Storage',
        theme: 'data',
        description: 'Sensitive data is stored on the device in a form another app, or anyone with physical access, can read.',
        techniques: ['Insecure Data Storage', 'Unencrypted Local Database'],
      },
      {
        code: 'M10',
        name: 'Insufficient Cryptography',
        theme: 'data',
        description: 'Encryption is attempted but implemented with weak algorithms, hardcoded keys, or other flawed practices.',
        techniques: ['Weak Encryption Algorithms', 'Hardcoded Keys'],
      },
    ],
  },

  smartcontract2023: {
    track: 'smart-contract',
    year: 2023,
    label: 'OWASP Smart Contract Top 10',
    sourceUrl: 'https://scs.owasp.org/sctop10/archive/2023/Top10:2023/',
    categories: [
      {
        code: 'SC01',
        name: 'Reentrancy Attacks',
        theme: 'design',
        description: 'A contract calls out to another contract before finishing its own state updates, letting the callee call back in and repeat an action using stale state.',
        techniques: ['Reentrancy Attack', 'Cross-Function Reentrancy'],
      },
      {
        code: 'SC02',
        name: 'Integer Overflow and Underflow',
        theme: 'injection',
        description: 'Arithmetic on a fixed-size integer exceeds its range and silently wraps around, producing a wildly wrong value.',
        techniques: ['Integer Overflow', 'Integer Underflow'],
      },
      {
        code: 'SC03',
        name: 'Timestamp Dependence',
        theme: 'design',
        description: 'Contract logic depends on the block timestamp for something security-sensitive, but miners have some latitude to influence it.',
        techniques: ['Timestamp Dependence', 'Block Timestamp Manipulation'],
      },
      {
        code: 'SC04',
        name: 'Access Control Vulnerabilities',
        theme: 'access',
        description: 'A contract\'s privileged functions aren\'t properly restricted to the intended caller.',
        techniques: ['Missing Access Control Modifier', 'tx.origin Authorization Bypass'],
      },
      {
        code: 'SC05',
        name: 'Front-running Attacks',
        theme: 'design',
        description: 'Since pending transactions are visible before confirmation, an attacker can see a profitable transaction and submit their own with higher gas to execute first.',
        techniques: ['Front-Running Attack', 'MEV Sandwich Attack'],
      },
      {
        code: 'SC06',
        name: 'Denial of Service (DoS) Attacks',
        theme: 'design',
        description: 'A contract can be made to consume excessive gas or revert unexpectedly, blocking its normal use for everyone.',
        techniques: ['Gas Limit DoS', 'Unbounded Loop DoS'],
      },
      {
        code: 'SC07',
        name: 'Logic Errors',
        theme: 'design',
        description: 'The contract\'s behavior deviates from its intended design — wrong reward math, flawed lending logic, or similar.',
        techniques: ['Flawed Business Logic'],
      },
      {
        code: 'SC08',
        name: 'Insecure Randomness',
        theme: 'data',
        description: 'A blockchain is deterministic by design, so sourcing "randomness" from on-chain values an attacker can predict or influence isn\'t actually random.',
        techniques: ['Predictable Randomness', 'Blockhash-based Randomness Exploit'],
      },
      {
        code: 'SC09',
        name: 'Gas Limit Vulnerabilities',
        theme: 'design',
        description: 'Operations (often loops over growing on-chain data) eventually exceed the block gas limit and can never complete.',
        techniques: ['Gas Limit DoS'],
      },
      {
        code: 'SC10',
        name: 'Unchecked External Calls',
        theme: 'injection',
        description: 'The return value of a call to another contract isn\'t checked, so a failed call is silently treated as if it succeeded.',
        techniques: ['Unchecked External Calls', 'Unchecked Call Return Value'],
      },
    ],
  },

  smartcontract2025: {
    track: 'smart-contract',
    year: 2025,
    label: 'OWASP Smart Contract Top 10',
    sourceUrl: 'https://scs.owasp.org/sctop10/archive/2025/Top10:2025/',
    categories: [
      {
        code: 'SC01',
        name: 'Access Control Vulnerabilities',
        theme: 'access',
        changeNote: 'Jumped from #4 in 2023 to #1 — the single costliest category, responsible for over $950M in losses in the data behind this edition.',
        description: 'A contract\'s privileged functions aren\'t properly restricted to the intended caller.',
        techniques: ['Missing Access Control Modifier', 'tx.origin Authorization Bypass'],
      },
      {
        code: 'SC02',
        name: 'Price Oracle Manipulation',
        theme: 'data',
        changeNote: 'New entry — wasn\'t a named 2023 category, reflecting how central price feeds have become to DeFi exploits.',
        description: 'A contract trusts an external price feed that can itself be manipulated, skewing every calculation built on top of it.',
        techniques: ['Price Oracle Manipulation', 'Flash Loan Price Manipulation'],
      },
      {
        code: 'SC03',
        name: 'Logic Errors',
        theme: 'design',
        description: 'The contract\'s behavior deviates from its intended design — wrong reward math, flawed lending logic, or similar.',
        techniques: ['Flawed Business Logic'],
      },
      {
        code: 'SC04',
        name: 'Lack of Input Validation',
        theme: 'injection',
        description: 'A contract accepts attacker-supplied values without validating them, letting malformed or malicious input break its logic.',
        techniques: ['Insufficient Input/Output Validation'],
      },
      {
        code: 'SC05',
        name: 'Reentrancy Attacks',
        theme: 'design',
        description: 'A contract calls out to another contract before finishing its own state updates, letting the callee call back in and repeat an action using stale state.',
        techniques: ['Reentrancy Attack', 'Cross-Function Reentrancy'],
      },
      {
        code: 'SC06',
        name: 'Unchecked External Calls',
        theme: 'injection',
        description: 'The return value of a call to another contract isn\'t checked, so a failed call is silently treated as if it succeeded.',
        techniques: ['Unchecked External Calls', 'Unchecked Call Return Value'],
      },
      {
        code: 'SC07',
        name: 'Flash Loan Attacks',
        theme: 'design',
        changeNote: 'New entry — flash loans let an attacker borrow enormous, uncollateralized capital for a single transaction to manipulate a protocol.',
        description: 'An attacker borrows a very large, uncollateralized sum for one transaction to briefly distort a protocol\'s state, profits from the distortion, then repays the loan.',
        techniques: ['Flash Loan Attack'],
      },
      {
        code: 'SC08',
        name: 'Integer Overflow and Underflow',
        theme: 'injection',
        description: 'Arithmetic on a fixed-size integer exceeds its range and silently wraps around, producing a wildly wrong value.',
        techniques: ['Integer Overflow', 'Integer Underflow'],
      },
      {
        code: 'SC09',
        name: 'Insecure Randomness',
        theme: 'data',
        description: 'A blockchain is deterministic by design, so sourcing "randomness" from on-chain values an attacker can predict or influence isn\'t actually random.',
        techniques: ['Predictable Randomness', 'Blockhash-based Randomness Exploit'],
      },
      {
        code: 'SC10',
        name: 'Denial of Service (DoS) Attacks',
        theme: 'design',
        changeNote: 'Merges 2023\'s separate "Gas Limit Vulnerabilities" (SC09) into this category — dropped Timestamp Dependence and Front-running entirely as standalone entries.',
        description: 'A contract can be made to consume excessive gas or revert unexpectedly, blocking its normal use for everyone.',
        techniques: ['Gas Limit DoS', 'Unbounded Loop DoS'],
      },
    ],
  },

  smartcontract2026: {
    track: 'smart-contract',
    year: 2026,
    label: 'OWASP Smart Contract Top 10',
    sourceUrl: 'https://scs.owasp.org/sctop10/',
    categories: [
      {
        code: 'SC01',
        name: 'Access Control Vulnerabilities',
        theme: 'access',
        description: 'A contract\'s privileged functions aren\'t properly restricted to the intended caller.',
        techniques: ['Missing Access Control Modifier', 'tx.origin Authorization Bypass'],
      },
      {
        code: 'SC02',
        name: 'Business Logic Vulnerabilities',
        theme: 'design',
        changeNote: 'Renamed from "Logic Errors."',
        description: 'The contract\'s behavior deviates from its intended design — wrong reward math, flawed lending logic, or similar.',
        techniques: ['Flawed Business Logic'],
      },
      {
        code: 'SC03',
        name: 'Price Oracle Manipulation',
        theme: 'data',
        description: 'A contract trusts an external price feed that can itself be manipulated, skewing every calculation built on top of it.',
        techniques: ['Price Oracle Manipulation', 'Flash Loan Price Manipulation'],
      },
      {
        code: 'SC04',
        name: 'Flash Loan–Facilitated Attacks',
        theme: 'design',
        description: 'An attacker borrows a very large, uncollateralized sum for one transaction to briefly distort a protocol\'s state, profits from the distortion, then repays the loan.',
        techniques: ['Flash Loan Attack'],
      },
      {
        code: 'SC05',
        name: 'Lack of Input Validation',
        theme: 'injection',
        description: 'A contract accepts attacker-supplied values without validating them, letting malformed or malicious input break its logic.',
        techniques: ['Insufficient Input/Output Validation'],
      },
      {
        code: 'SC06',
        name: 'Unchecked External Calls',
        theme: 'injection',
        description: 'The return value of a call to another contract isn\'t checked, so a failed call is silently treated as if it succeeded.',
        techniques: ['Unchecked External Calls', 'Unchecked Call Return Value'],
      },
      {
        code: 'SC07',
        name: 'Arithmetic Errors (Rounding & Precision)',
        theme: 'injection',
        changeNote: 'New entry, split out from general integer overflow — precision loss in division and rounding direction is a distinct bug class.',
        description: 'Fixed-point math loses precision or rounds in the wrong direction, letting an attacker profit from the accumulated error.',
        techniques: ['Rounding Direction Exploit', 'Precision Loss in Division'],
      },
      {
        code: 'SC08',
        name: 'Reentrancy Attacks',
        theme: 'design',
        description: 'A contract calls out to another contract before finishing its own state updates, letting the callee call back in and repeat an action using stale state.',
        techniques: ['Reentrancy Attack', 'Cross-Function Reentrancy'],
      },
      {
        code: 'SC09',
        name: 'Integer Overflow and Underflow',
        theme: 'injection',
        description: 'Arithmetic on a fixed-size integer exceeds its range and silently wraps around, producing a wildly wrong value.',
        techniques: ['Integer Overflow', 'Integer Underflow'],
      },
      {
        code: 'SC10',
        name: 'Proxy & Upgradeability Vulnerabilities',
        theme: 'design',
        changeNote: 'Brand-new category — upgradeable contract patterns (proxies) introduce their own distinct risk class around storage layout and initialization.',
        description: 'Upgradeable contracts route calls through a proxy; mismatched storage layouts or unprotected upgrade functions between versions can corrupt state or hand control to an attacker.',
        techniques: ['Storage Layout Collision', 'Unprotected Upgrade Function'],
      },
    ],
  },
};

export function getEdition(key) {
  return EDITIONS[key];
}
