// Detailed, structured write-ups for attack techniques referenced by chips
// in AttackAtlas/data.js. Content is original (written for this site, not
// copied from any source) and deliberately reads beginner → expert
// top-to-bottom: Overview (what it is) → How It Works (the flow) →
// Types & Variants (depth) → Vulnerable vs Fixed code (where available) →
// How To Defend (practical).
//
// cwe: the official MITRE CWE identifier, where one clear match exists.
// Omitted (rather than guessed) for categories that don't map to a single
// CWE — a business-logic flaw or an inventory-management gap genuinely
// isn't one specific weakness type.
//
// vaultWeakness: the exact `weakness` string(s) used in Bounty Vault's
// HackerOne dataset, so a reader can jump straight to real disclosed
// reports of this type. Only set where a confident, accurate match exists
// against HackerOne's own weakness taxonomy — left unset rather than
// force-matched to something approximate.
//
// code: a short vulnerable/fixed snippet pair, illustrative only.
//
// ALIASES maps every chip label that ever appears in data.js to one of
// these canonical entries, since many labels ("SQL Injection" vs "SQL
// Injection via API Params") are really the same underlying technique.

export const TECHNIQUES = {
  'sql-injection': {
    title: 'SQL Injection',
    cwe: 'CWE-89',
    vaultWeakness: ['SQL Injection'],
    summary: 'Untrusted input is inserted directly into a database query, letting an attacker change what the query actually does — read data they shouldn\'t see, bypass a login, or modify records.',
    howItWorks: [
      'An app builds a SQL query by concatenating user input directly into the query string, instead of treating input as data.',
      'The attacker submits input containing SQL syntax (like a stray quote or a SQL keyword) instead of a normal value.',
      'The database parses the attacker\'s syntax as part of the query itself, not as a harmless string.',
      'The query now does something different than intended — returning extra rows, bypassing a WHERE clause, or executing a second statement.',
    ],
    types: [
      {name: 'In-band (classic)', description: 'The result of the injection is returned directly in the app\'s response — the fastest and easiest to spot.'},
      {name: 'Blind (boolean-based)', description: 'No data is returned directly; the attacker infers true/false answers from how the page behaves (e.g. does it load normally or show an error).'},
      {name: 'Blind (time-based)', description: 'The attacker injects a deliberate delay (e.g. a SLEEP() call) and measures response time to infer answers one bit at a time.'},
      {name: 'Out-of-band', description: 'Results are exfiltrated through a separate channel, like a DNS lookup, when direct or blind extraction isn\'t practical.'},
    ],
    code: {
      language: 'js',
      vulnerable: "const query = `SELECT * FROM users WHERE username = '${username}' AND password = '${password}'`;\ndb.query(query);",
      fixed: "const query = 'SELECT * FROM users WHERE username = ? AND password = ?';\ndb.query(query, [username, password]);",
    },
    defenses: ['Parameterized queries / prepared statements (never string-concatenate input into SQL)', 'Least-privilege database accounts for the app', 'Input validation as defense-in-depth, not the primary control', 'A WAF as a compensating control, not a substitute for fixing the query'],
  },
  'command-injection': {
    title: 'Command Injection',
    cwe: 'CWE-78',
    vaultWeakness: ['Command Injection - Generic', 'OS Command Injection'],
    summary: 'User input reaches a system shell command, letting an attacker run their own OS commands with the application\'s privileges.',
    howItWorks: [
      'An app passes user input into a function that executes a shell command (e.g. to ping a host or process a file).',
      'The attacker includes shell metacharacters (like `;`, `|`, or `&&`) in their input.',
      'The shell interprets those characters as command separators, not literal text.',
      'A second, attacker-controlled command runs alongside (or instead of) the intended one.',
    ],
    types: [
      {name: 'Classic injection', description: 'Chaining a new command onto the intended one with `;`, `&&`, or `|`.'},
      {name: 'Blind injection', description: 'No output is returned; the attacker confirms execution via time delays or out-of-band callbacks.'},
      {name: 'Argument injection', description: 'Instead of chaining commands, the attacker manipulates flags/arguments passed to the intended binary.'},
    ],
    code: {
      language: 'js',
      vulnerable: "const { exec } = require('child_process');\nexec(`ping -c 4 ${userInput}`);",
      fixed: "const { execFile } = require('child_process');\nexecFile('ping', ['-c', '4', userInput]);",
    },
    defenses: ['Avoid shell execution entirely; use language-native APIs instead', 'If unavoidable, use an allowlist of exact arguments, never string concatenation', 'Run with the least OS privilege necessary', 'Sandbox or containerize processes that must shell out'],
  },
  'ldap-injection': {
    title: 'LDAP Injection',
    cwe: 'CWE-90',
    summary: 'Untrusted input is inserted into an LDAP query (used for directory/authentication lookups), letting an attacker alter the filter logic.',
    howItWorks: [
      'An app builds an LDAP search filter using user input (e.g. a username in a login form).',
      'The attacker includes LDAP filter syntax like `*` or `)(`.',
      'The directory server interprets this as filter logic, not a literal value.',
      'The search returns more results than intended, or bypasses an authentication check entirely.',
    ],
    types: [
      {name: 'Authentication bypass', description: 'Crafting a filter that always evaluates true, regardless of the real credentials.'},
      {name: 'Information disclosure', description: 'Broadening a search filter to enumerate directory entries the attacker shouldn\'t see.'},
    ],
    defenses: ['Use parameterized LDAP APIs where available', 'Escape LDAP special characters in user input', 'Apply least-privilege bind accounts for searches'],
  },
  'xpath-injection': {
    title: 'XPath Injection',
    cwe: 'CWE-643',
    summary: 'Untrusted input is inserted into an XPath query against an XML document, letting an attacker alter which nodes the query selects.',
    howItWorks: [
      'An app queries an XML document using XPath built from user input.',
      'The attacker injects XPath syntax to change the query\'s logic.',
      'The query selects unintended nodes — bypassing a check or exposing other data in the document.',
    ],
    types: [
      {name: 'Boolean-based blind', description: 'Inferring document structure or data one true/false answer at a time.'},
      {name: 'Authentication bypass', description: 'Crafting a predicate that always matches, similar in spirit to SQLi login bypass.'},
    ],
    defenses: ['Use parameterized XPath queries', 'Validate and escape input before building any query', 'Avoid storing sensitive data in XML documents queried this way'],
  },
  'nosql-injection': {
    title: 'NoSQL Injection',
    cwe: 'CWE-943',
    summary: 'Untrusted input is passed into a NoSQL database query (like MongoDB) as a structured object instead of a plain value, letting an attacker alter query logic using the database\'s own operators.',
    howItWorks: [
      'An app accepts input (often JSON) and passes it into a query without validating its structure.',
      'The attacker submits an object using the database\'s query operators (e.g. `{"$ne": null}`) instead of a plain string.',
      'The database evaluates the operator as query logic, not a literal value.',
      'The query matches unintended documents — commonly bypassing authentication.',
    ],
    types: [
      {name: 'Operator injection', description: 'Using operators like $ne, $gt, or $regex to alter comparison logic.'},
      {name: 'JavaScript injection', description: 'In databases that support server-side JS execution in queries, injecting code to run arbitrary logic.'},
    ],
    defenses: ['Enforce strict input types (reject objects where a string is expected)', 'Use an ODM/query builder that separates structure from data', 'Disable server-side JS execution in the database if not required'],
  },
  xss: {
    title: 'Cross-Site Scripting (XSS)',
    cwe: 'CWE-79',
    vaultWeakness: ['Cross-site Scripting (XSS) - Stored', 'Cross-site Scripting (XSS) - Generic', 'Cross-site Scripting (XSS) - Reflected', 'Cross-site Scripting (XSS) - DOM'],
    summary: 'Untrusted data is rendered in a browser without proper escaping, letting an attacker\'s script run inside another user\'s session — reading their cookies, acting as them, or defacing the page.',
    howItWorks: [
      'An app takes input (a comment, a search term, a URL parameter) and includes it in an HTML page.',
      'The input isn\'t properly escaped for the context it\'s placed in.',
      'A victim\'s browser renders the attacker\'s payload as real HTML/JavaScript, not inert text.',
      'The script runs with the victim\'s privileges on that site — stealing session tokens, making requests as them, or altering the page.',
    ],
    types: [
      {name: 'Reflected XSS', description: 'The payload comes from the current request (e.g. a URL parameter) and is reflected straight back into the response, requiring the victim to click a crafted link.'},
      {name: 'Stored XSS', description: 'The payload is saved server-side (e.g. in a comment) and served to every visitor who views that content — no crafted link needed.'},
      {name: 'DOM-based XSS', description: 'The vulnerable code runs entirely in client-side JavaScript, manipulating the page\'s DOM based on untrusted input, without the server ever seeing the payload.'},
      {name: 'Mutation XSS (mXSS)', description: 'A payload that looks safe when checked, but is "mutated" into a dangerous form once the browser\'s HTML parser processes it.'},
    ],
    code: {
      language: 'jsx',
      vulnerable: '<div dangerouslySetInnerHTML={{ __html: comment.text }} />',
      fixed: '<div>{comment.text}</div>  {/* React escapes this automatically */}',
    },
    defenses: ['Context-aware output encoding (HTML, attribute, JS, and URL contexts each need different escaping)', 'A strict Content-Security-Policy', 'Use frameworks that auto-escape by default (React, etc.) and avoid `dangerouslySetInnerHTML`-style escape hatches', 'HttpOnly cookies to limit what a successful XSS can steal'],
  },
  idor: {
    title: 'Insecure Direct Object Reference (IDOR)',
    cwe: 'CWE-639',
    vaultWeakness: ['Insecure Direct Object Reference (IDOR)'],
    summary: 'An app lets a user access an object (a file, record, or account) by its ID, but doesn\'t check whether that user is actually allowed to access it.',
    howItWorks: [
      'A request references an object directly by its ID (e.g. `/invoices/1042`).',
      'The server fetches and returns the object matching that ID.',
      'The server never checks whether the requesting user actually owns or is authorized to view that specific object.',
      'An attacker simply changes the ID (`1042` → `1043`) and receives someone else\'s data.',
    ],
    types: [
      {name: 'Sequential ID enumeration', description: 'IDs are predictable integers, so an attacker can iterate through a whole range.'},
      {name: 'Object ID leakage', description: 'IDs aren\'t sequential, but are exposed elsewhere (emails, other API responses) and reused directly.'},
      {name: 'IDOR in write operations', description: 'The same missing check applies to an update or delete request, not just a read.'},
    ],
    code: {
      language: 'js',
      vulnerable: "app.get('/invoices/:id', (req, res) => {\n  const invoice = db.getInvoice(req.params.id);\n  res.json(invoice);\n});",
      fixed: "app.get('/invoices/:id', (req, res) => {\n  const invoice = db.getInvoice(req.params.id);\n  if (invoice.userId !== req.user.id) return res.status(403).end();\n  res.json(invoice);\n});",
    },
    defenses: ['Check ownership/authorization server-side on every object access, every time', 'Use indirect references (session-scoped tokens) instead of raw database IDs where practical', 'Apply the same authorization check consistently to read, write, and delete paths'],
  },
  'privilege-escalation': {
    title: 'Privilege Escalation',
    cwe: 'CWE-269',
    vaultWeakness: ['Privilege Escalation'],
    summary: 'An attacker gains access to functionality or data beyond what their account is supposed to have — either another user\'s data (horizontal) or an admin-level capability (vertical).',
    howItWorks: [
      'An application restricts certain data or actions to specific users or roles.',
      'That restriction is enforced inconsistently — sometimes checked in the UI, but not on every backend endpoint.',
      'An attacker calls the underlying endpoint directly, or manipulates a parameter (role, user ID) that the server trusts without re-verifying.',
      'The server performs the privileged action or returns the restricted data anyway.',
    ],
    types: [
      {name: 'Horizontal escalation', description: 'Accessing another user\'s data at the same privilege level (closely related to IDOR).'},
      {name: 'Vertical escalation', description: 'Gaining a higher privilege level entirely — a regular user reaching admin functionality.'},
      {name: 'Admin endpoint access as regular user', description: 'Calling an admin-only API route directly, bypassing a UI that simply hides the button.'},
    ],
    defenses: ['Enforce authorization server-side on every request, never rely on hiding UI elements', 'Centralize authorization logic instead of re-implementing per-endpoint', 'Apply least privilege by default for new accounts and roles'],
  },
  'cors-misconfig': {
    title: 'CORS Misconfiguration',
    cwe: 'CWE-942',
    summary: 'A server\'s Cross-Origin Resource Sharing policy is set too permissively, letting untrusted websites make authenticated requests to it on a victim\'s behalf.',
    howItWorks: [
      'A server sets `Access-Control-Allow-Origin` to reflect any requesting origin, or to `*` combined with credentials.',
      'An attacker hosts a malicious page that makes a cross-origin request to the target API from a logged-in victim\'s browser.',
      'The browser allows the response to be read by the attacker\'s page because the server\'s CORS headers say it\'s fine.',
      'The attacker\'s script reads sensitive data or performs actions using the victim\'s active session.',
    ],
    types: [
      {name: 'Origin reflection', description: 'The server blindly echoes whatever Origin header the browser sent back into Access-Control-Allow-Origin.'},
      {name: 'Wildcard with credentials', description: 'Combining `*` with `Access-Control-Allow-Credentials: true` — invalid per spec but sometimes shipped anyway via misconfigured proxies.'},
      {name: 'Null origin allowance', description: 'Trusting the `null` origin, which is trivially spoofable from sandboxed iframes or local files.'},
    ],
    code: {
      language: 'js',
      vulnerable: "app.use((req, res, next) => {\n  res.header('Access-Control-Allow-Origin', req.headers.origin);\n  res.header('Access-Control-Allow-Credentials', 'true');\n  next();\n});",
      fixed: "const ALLOWED = ['https://app.example.com'];\napp.use((req, res, next) => {\n  if (ALLOWED.includes(req.headers.origin)) {\n    res.header('Access-Control-Allow-Origin', req.headers.origin);\n    res.header('Access-Control-Allow-Credentials', 'true');\n  }\n  next();\n});",
    },
    defenses: ['Use an explicit allowlist of trusted origins, never reflect or wildcard with credentials', 'Only enable credentials mode where genuinely required', 'Treat CORS as an access-control decision, not a formality'],
  },
  'forced-browsing': {
    title: 'Forced Browsing',
    cwe: 'CWE-425',
    vaultWeakness: ['Improper Access Control - Generic'],
    summary: 'An attacker directly requests URLs or resources that aren\'t linked from the UI, hoping the server enforces no additional access check on them.',
    howItWorks: [
      'A resource exists at a predictable or guessable URL (e.g. `/admin`, `/backup.zip`, `/user/settings?id=5`).',
      'The application relies on the UI simply not linking to it, rather than checking access server-side.',
      'The attacker requests the URL directly, skipping the normal navigation flow entirely.',
      'The server serves the resource with no further check.',
    ],
    types: [
      {name: 'Hidden admin panels', description: 'Administrative interfaces reachable by URL guessing, with no separate authentication gate.'},
      {name: 'Exposed backup/config files', description: 'Files like `.env`, `.git/`, or database dumps left reachable in a web root.'},
    ],
    defenses: ['Never rely on "security through obscurity" for sensitive paths', 'Enforce authentication/authorization at the server for every route', 'Keep build artifacts, backups, and version-control directories out of the web root entirely'],
  },
  ssrf: {
    title: 'Server-Side Request Forgery (SSRF)',
    cwe: 'CWE-918',
    vaultWeakness: ['Server-Side Request Forgery (SSRF)'],
    summary: 'An application fetches a URL supplied (directly or indirectly) by the user, letting an attacker make the server issue requests to places it shouldn\'t — internal services, cloud metadata endpoints, or other systems.',
    howItWorks: [
      'A feature accepts a URL from the user (e.g. "fetch this image," "check this webhook," a PDF-generation tool that loads a page).',
      'The server fetches that URL as itself, from inside the trusted network.',
      'The attacker points the URL at an internal address instead of a real external resource (a private IP, `localhost`, or a cloud metadata endpoint).',
      'The internal service responds, and that response — often containing secrets or access to internal-only systems — flows back to the attacker.',
    ],
    types: [
      {name: 'Basic SSRF', description: 'The response is returned directly to the attacker in the app\'s output.'},
      {name: 'Blind SSRF', description: 'No response is shown, but the attacker confirms the request happened via timing or an out-of-band callback (e.g. a DNS/HTTP ping to a server they control).'},
      {name: 'Cloud metadata access', description: 'Targeting a cloud provider\'s internal metadata endpoint (like `169.254.169.254`) to steal instance credentials.'},
      {name: 'Filter bypass via encoding', description: 'Using decimal/hex IP encoding, DNS rebinding, or redirects to evade a naive blocklist on the target URL.'},
    ],
    code: {
      language: 'js',
      vulnerable: "app.post('/fetch-preview', async (req, res) => {\n  const response = await fetch(req.body.url);\n  res.send(await response.text());\n});",
      fixed: "app.post('/fetch-preview', async (req, res) => {\n  const url = new URL(req.body.url);\n  if (!ALLOWED_HOSTS.includes(url.hostname)) return res.status(400).end();\n  const response = await fetch(url);\n  res.send(await response.text());\n});",
    },
    defenses: ['Validate destination URLs against an allowlist of expected hosts, not a denylist', 'Block requests to private/link-local IP ranges at the network layer, not just in application code', 'Disable unnecessary URL-fetching features entirely where not needed', 'For cloud environments, use metadata service versions that require an explicit token (like IMDSv2)'],
  },
  xxe: {
    title: 'XML External Entities (XXE)',
    cwe: 'CWE-611',
    vaultWeakness: ['XML External Entities (XXE)'],
    summary: 'A poorly configured XML parser processes external entity references in an XML document, letting an attacker read local files, trigger internal requests, or crash the service.',
    howItWorks: [
      'An application accepts XML input and parses it with a parser that has external entity resolution enabled (the historical default in many XML libraries).',
      'The attacker defines a custom entity in a DOCTYPE declaration pointing at a file or URL.',
      'The attacker references that entity elsewhere in the document.',
      'The parser resolves it, substituting the content of the referenced file or the response of the referenced URL into the document.',
    ],
    types: [
      {name: 'File disclosure', description: 'Defining an entity that points at a local file (like `/etc/passwd`), returned in the parsed output.'},
      {name: 'XXE-based SSRF', description: 'Pointing the entity at an internal URL instead of a file, turning XXE into an SSRF primitive.'},
      {name: 'Billion Laughs (XML bomb)', description: 'Nested entity definitions that expand exponentially, exhausting memory and causing denial of service.'},
      {name: 'Blind XXE via out-of-band channel', description: 'When output isn\'t reflected, exfiltrating data via a DNS or HTTP request the entity triggers to an attacker-controlled server.'},
    ],
    code: {
      language: 'python',
      vulnerable: "from lxml import etree\ntree = etree.parse(user_supplied_xml)",
      fixed: "from lxml import etree\nparser = etree.XMLParser(resolve_entities=False, no_network=True)\ntree = etree.parse(user_supplied_xml, parser)",
    },
    defenses: ['Disable external entity and DTD processing in the XML parser entirely — this is the real fix', 'Prefer data formats like JSON where XML isn\'t specifically required', 'Keep XML libraries patched, since safe defaults have improved over time but older configs linger'],
  },
  'insecure-deserialization': {
    title: 'Insecure Deserialization',
    cwe: 'CWE-502',
    vaultWeakness: ['Deserialization of Untrusted Data'],
    summary: 'An application deserializes untrusted data into objects without validation, and the deserialization process itself can be abused to execute code or tamper with application logic.',
    howItWorks: [
      'An app accepts a serialized object (often from a cookie, cache, or API payload) and deserializes it back into a native object.',
      'The deserialization process in many languages can trigger code execution as a side effect (e.g. via "magic methods" invoked automatically on object construction).',
      'The attacker crafts a serialized payload referencing classes already present in the application that have dangerous side effects.',
      'Deserializing that payload triggers unintended code execution or object state tampering.',
    ],
    types: [
      {name: 'Java deserialization RCE', description: 'Exploiting "gadget chains" — sequences of existing library classes — to achieve remote code execution when a malicious serialized object is deserialized.'},
      {name: 'PHP object injection', description: 'Crafting a serialized PHP object that invokes a class\'s magic methods (like `__wakeup` or `__destruct`) to unintended effect.'},
      {name: 'Python pickle exploitation', description: 'Python\'s `pickle` format can execute arbitrary code during deserialization by design — never unpickle untrusted data.'},
    ],
    code: {
      language: 'python',
      vulnerable: 'import pickle\ndata = pickle.loads(request_body)',
      fixed: 'import json\ndata = json.loads(request_body)  # plain data, no code execution risk',
    },
    defenses: ['Avoid deserializing untrusted data at all; prefer plain data formats like JSON with strict schemas', 'If deserialization of complex objects is unavoidable, use signing/integrity checks so tampered payloads are rejected before deserializing', 'Keep deserialization libraries patched and minimize "gadget"-capable classes on the classpath'],
  },
  'credential-stuffing': {
    title: 'Credential Stuffing',
    cwe: 'CWE-307',
    vaultWeakness: ['Improper Authentication - Generic', 'Improper Restriction of Authentication Attempts'],
    summary: 'An attacker automates login attempts using username/password pairs leaked from other breaches, betting that people reuse passwords across sites.',
    howItWorks: [
      'A large list of real username/password pairs from a previous, unrelated breach is obtained.',
      'The attacker automates login attempts against the target site using that list.',
      'Because password reuse is common, a meaningful percentage of accounts succeed even though the target itself was never breached.',
      'Successful logins are harvested for account takeover.',
    ],
    types: [
      {name: 'Distributed/low-and-slow', description: 'Spreading attempts across many IPs and over time to evade rate-limiting and anomaly detection.'},
      {name: 'Credential spraying', description: 'A close relative: trying a small number of common passwords against many different usernames, instead of many passwords against one.'},
    ],
    defenses: ['Multi-factor authentication — the single most effective mitigation', 'Rate limiting and CAPTCHA on login endpoints', 'Detect and block known-breached credentials at signup/login (credential screening services)', 'Monitor for distributed login attempts against the same account'],
  },
  'brute-force': {
    title: 'Brute Force',
    cwe: 'CWE-307',
    vaultWeakness: ['Improper Restriction of Authentication Attempts', 'Improper Authentication - Generic'],
    summary: 'An attacker systematically tries many password (or other secret) guesses against an endpoint until one works.',
    howItWorks: [
      'An endpoint accepts repeated authentication attempts with no meaningful limit.',
      'The attacker automates guesses — either a full keyspace search or a targeted wordlist.',
      'Each attempt is checked by the server with no increasing friction or lockout.',
      'Eventually a correct guess succeeds.',
    ],
    types: [
      {name: 'Dictionary attack', description: 'Trying a curated list of common/likely passwords rather than exhausting the full keyspace.'},
      {name: 'Unrestricted API brute force', description: 'The same pattern applied to an API endpoint with no rate limit, rather than a login form.'},
    ],
    defenses: ['Rate limit and progressively delay repeated failed attempts', 'Lock or challenge (CAPTCHA/MFA) accounts after a threshold of failures', 'Use strong, salted password hashing so even a stolen hash resists offline brute force'],
  },
  'session-attacks': {
    title: 'Session Fixation & Token Weaknesses',
    cwe: 'CWE-384',
    vaultWeakness: ['Insufficient Session Expiration'],
    summary: 'Weaknesses in how session identifiers are generated, transmitted, or rotated let an attacker hijack or predict another user\'s session.',
    howItWorks: [
      'A session ID is issued to identify a logged-in user for subsequent requests.',
      'If the ID is predictable, exposed in a URL, or not rotated after login, an attacker can obtain or guess a victim\'s active session ID.',
      'The attacker presents that session ID as their own.',
      'The server treats the attacker as the legitimate, already-authenticated user.',
    ],
    types: [
      {name: 'Session fixation', description: 'The attacker sets a known session ID on the victim before login, then reuses that same ID once the victim authenticates.'},
      {name: 'Session ID in URL', description: 'Putting the session token in the URL leaks it via browser history, referrer headers, and server logs.'},
      {name: 'Weak/predictable tokens', description: 'Session IDs generated with insufficient randomness can be guessed outright.'},
    ],
    defenses: ['Regenerate the session ID on every privilege change, especially login', 'Never place session identifiers in the URL — use cookies with HttpOnly and Secure flags', 'Generate session tokens with a cryptographically secure random source'],
  },
  'password-recovery': {
    title: 'Weak Password Recovery',
    cwe: 'CWE-640',
    summary: 'A password reset flow has a logic flaw — a guessable token, a weak security question, or a step that can be skipped — letting an attacker take over an account without knowing the password.',
    howItWorks: [
      'A user requests a password reset, and the app issues a token or code to prove identity.',
      'That proof mechanism is weak: short/guessable codes, tokens that don\'t expire, or questions with publicly discoverable answers.',
      'The attacker either guesses the proof or answers the security question using public information about the victim.',
      'The attacker completes the reset flow and sets a new password, locking the real user out.',
    ],
    types: [
      {name: 'Guessable reset tokens', description: 'Short numeric codes or sequential tokens that can be brute-forced.'},
      {name: 'Weak security questions', description: 'Questions with answers that are public record or easily researched.'},
      {name: 'Response manipulation', description: 'Tampering with a client-side "reset allowed: true/false" style response instead of a properly server-enforced flow.'},
    ],
    defenses: ['Use long, random, single-use, short-lived reset tokens sent only to a verified channel', 'Avoid security questions as a primary factor', 'Rate-limit reset attempts and notify the account owner of any reset request'],
  },
  'mfa-bypass': {
    title: 'MFA Bypass',
    cwe: 'CWE-287',
    summary: 'A flaw in how multi-factor authentication is implemented lets an attacker complete login without actually satisfying the second factor.',
    howItWorks: [
      'A login flow checks a password, then separately checks an MFA code.',
      'The two steps aren\'t properly linked — the server doesn\'t verify that a session which passed step 1 is the same one completing step 2, or a race condition/logic flaw lets an attacker skip straight to a post-MFA state.',
      'The attacker exploits that gap to reach an authenticated state without a valid second factor.',
    ],
    types: [
      {name: 'Response manipulation', description: 'Intercepting and altering an API response (e.g. `"mfa_required": true` → `false`) that the client trusts.'},
      {name: 'Endpoint skipping', description: 'Calling a later-stage endpoint directly, bypassing the MFA check entirely because it isn\'t re-verified server-side.'},
      {name: 'Backup-code/recovery abuse', description: 'Exploiting a weaker recovery path that doesn\'t enforce the same MFA requirement.'},
    ],
    defenses: ['Enforce MFA state entirely server-side, never trust a client-supplied flag', 'Ensure every authenticated endpoint re-checks that MFA was actually completed for that session', 'Apply the same rigor to backup/recovery flows as the primary login path'],
  },
  'jwt-attacks': {
    title: 'JWT Tampering',
    cwe: 'CWE-347',
    summary: 'Weaknesses in how a JSON Web Token is validated let an attacker forge or modify a token\'s claims — such as their user ID or role — and have it accepted as legitimate.',
    howItWorks: [
      'A server issues a signed JWT after login and trusts its contents on later requests.',
      'The server\'s validation logic has a flaw — accepting an unsigned token, using a weak key, or not checking the signature at all.',
      'The attacker modifies the token\'s payload (e.g. changing their role to "admin") and either strips the signature or forges a new one.',
      'The server accepts the tampered token and grants access based on its (now false) claims.',
    ],
    types: [
      {name: '"none" algorithm attack', description: 'Setting the token\'s algorithm header to "none," and some libraries historically accepted it and skipped signature verification entirely.'},
      {name: 'Algorithm confusion (RS256→HS256)', description: 'Tricking a server that expects an asymmetric signature into verifying with its own public key treated as an HMAC secret.'},
      {name: 'Weak signing secret', description: 'A short or guessable HMAC secret that can be brute-forced offline, letting the attacker sign their own tokens.'},
      {name: 'Token replay', description: 'Reusing a captured valid token beyond its intended lifetime because the server doesn\'t properly check expiry or revocation.'},
    ],
    code: {
      language: 'js',
      vulnerable: "const decoded = jwt.decode(token); // no verification at all\nif (decoded.role === 'admin') { /* ... */ }",
      fixed: "const decoded = jwt.verify(token, SECRET, { algorithms: ['HS256'] });\nif (decoded.role === 'admin') { /* ... */ }",
    },
    defenses: ['Explicitly allowlist the expected signing algorithm — never trust the algorithm named in the token itself', 'Use strong, sufficiently long signing secrets (or asymmetric keys) and rotate them periodically', 'Set short expiries and implement real revocation for sensitive tokens', 'Use a well-maintained JWT library and keep it updated — most of these flaws were library-level bugs, now fixed'],
  },
  'cryptographic-failures': {
    title: 'Cryptographic Failures',
    cwe: 'CWE-327',
    vaultWeakness: ['Cryptographic Issues - Generic', 'Cleartext Storage of Sensitive Information', 'Cleartext Transmission of Sensitive Information', 'Insecure Storage of Sensitive Information', 'Improper Certificate Validation'],
    summary: 'Sensitive data is exposed because encryption is missing, weak, or implemented incorrectly — not because of a clever attack on the math itself, but because of how crypto was (mis)used.',
    howItWorks: [
      'Sensitive data (passwords, tokens, PII) needs protection at rest or in transit.',
      'A weak or outdated algorithm is used, a key is hardcoded or reused, or encryption is skipped entirely for "internal" data.',
      'An attacker who gains access to storage, traffic, or source code finds the data trivially readable or crackable.',
    ],
    types: [
      {name: 'Weak password hashing', description: 'Using fast, unsalted hashes like plain MD5 or SHA1 for passwords instead of a slow, salted algorithm designed for it (bcrypt, scrypt, Argon2).'},
      {name: 'Hardcoded keys/secrets', description: 'Encryption keys or API secrets committed directly into source code, visible to anyone with repo access.'},
      {name: 'Missing encryption at rest', description: 'Sensitive fields stored in plaintext in the database.'},
      {name: 'Downgrade attacks', description: 'Forcing a connection to fall back to an older, weaker protocol version or cipher suite that\'s already broken.'},
    ],
    code: {
      language: 'js',
      vulnerable: "const hash = crypto.createHash('md5').update(password).digest('hex');",
      fixed: "const hash = await bcrypt.hash(password, 12);",
    },
    defenses: ['Use modern, purpose-built algorithms: bcrypt/Argon2 for passwords, AES-GCM for data encryption', 'Never hardcode keys — use a secrets manager', 'Enforce TLS everywhere and disable legacy protocol/cipher fallbacks', 'Encrypt sensitive fields at rest, not just in transit'],
  },
  'mass-assignment': {
    title: 'Mass Assignment',
    cwe: 'CWE-915',
    summary: 'An API binds incoming request data directly to an internal object\'s fields, so an attacker can set fields they were never meant to control — like their own role or account balance.',
    howItWorks: [
      'An endpoint accepts a JSON body and automatically maps its fields onto a database model or object (a common framework convenience).',
      'The endpoint doesn\'t explicitly restrict which fields are allowed to be set this way.',
      'The attacker adds an extra field to the request body that isn\'t shown in the UI or documented — like `"isAdmin": true`.',
      'The framework happily sets that field too, since it wasn\'t told not to.',
    ],
    types: [
      {name: 'Overposting', description: 'Adding hidden/undocumented fields to a request body that the client-side form never exposes.'},
      {name: 'Excessive data exposure (the read-side mirror)', description: 'The related problem of an API *returning* more fields than intended, letting a client see data it shouldn\'t.'},
    ],
    code: {
      language: 'js',
      vulnerable: "app.post('/users/:id', (req, res) => {\n  User.findByIdAndUpdate(req.params.id, req.body);\n});",
      fixed: "app.post('/users/:id', (req, res) => {\n  const { name, email } = req.body; // explicit allowlist\n  User.findByIdAndUpdate(req.params.id, { name, email });\n});",
    },
    defenses: ['Use an explicit allowlist of bindable fields per endpoint — never bind the whole request body to a model', 'Apply the same allowlist discipline to response serialization, not just input', 'Review framework "convenience" auto-binding features specifically for this risk'],
  },
  'security-misconfiguration': {
    title: 'Security Misconfiguration',
    cwe: 'CWE-16',
    vaultWeakness: ['Misconfiguration', 'Information Exposure Through Directory Listing'],
    summary: 'A system is left in an insecure state — default settings, unnecessary features, exposed files, or overly detailed error messages — not because of a code flaw, but because of how it\'s configured and deployed.',
    howItWorks: [
      'A service is deployed with defaults that prioritize ease-of-setup over security (default admin passwords, sample apps left installed, verbose debug output).',
      'Nobody hardens the configuration before it goes live, or a later change accidentally re-enables something risky.',
      'An attacker scans for and finds the exposed default, feature, or information leak.',
      'They use it directly, or as a stepping stone to a deeper compromise.',
    ],
    types: [
      {name: 'Default credentials', description: 'Admin panels or services left with vendor-default usernames and passwords.'},
      {name: 'Exposed cloud storage / debug endpoints', description: 'Publicly readable storage buckets, or debug/profiling endpoints left enabled in production.'},
      {name: 'Missing security headers', description: 'Absent headers like Content-Security-Policy or X-Frame-Options that would otherwise blunt other attacks.'},
      {name: 'Verbose error messages', description: 'Stack traces or internal error details shown to end users, revealing implementation details useful for further attacks.'},
    ],
    defenses: ['Harden and review configurations before deployment, as a checklist, not an afterthought', 'Disable debug/verbose modes in production explicitly', 'Regularly scan for exposed storage, panels, and default credentials', 'Apply a strong baseline security header policy site-wide'],
  },
  'vulnerable-components': {
    title: 'Vulnerable and Outdated Components',
    cwe: 'CWE-1104',
    summary: 'An application uses a library, framework, or plugin with a known, publicly disclosed vulnerability, and hasn\'t patched it.',
    howItWorks: [
      'A project depends on third-party code — directly or transitively through other dependencies.',
      'A vulnerability is publicly disclosed (with a CVE) in one of those components.',
      'The application doesn\'t update to the patched version, sometimes for months or years.',
      'An attacker checks the exposed version (via headers, error pages, or fingerprinting) and applies a known, often public, exploit.',
    ],
    types: [
      {name: 'Direct dependency', description: 'The vulnerable library is one the project explicitly chose and imports.'},
      {name: 'Transitive dependency', description: 'The vulnerable code is pulled in indirectly by another dependency, often unnoticed.'},
      {name: 'Unsupported/end-of-life software', description: 'Running a version or product line that no longer receives security patches at all.'},
    ],
    defenses: ['Maintain an inventory of dependencies (an SBOM) so you know what you\'re actually running', 'Automate dependency vulnerability scanning in CI', 'Patch promptly once fixes are available — the exploit for a public CVE is often public too', 'Retire unsupported software rather than leaving it running'],
  },
  'supply-chain': {
    title: 'Software Supply Chain Attacks',
    cwe: 'CWE-1357',
    summary: 'Instead of attacking an application\'s own code, an attacker compromises something it depends on — a package, a build pipeline, or an update mechanism — so the malicious code arrives trusted, through the front door.',
    howItWorks: [
      'A project relies on external packages, a CI/CD pipeline, or an auto-update mechanism it implicitly trusts.',
      'An attacker compromises one of those trusted inputs — publishing a malicious package version, breaching a build server, or intercepting an update.',
      'Because the compromise arrives through a normally-trusted channel, it bypasses code review and typical perimeter defenses.',
      'The malicious code runs with whatever privilege the trusted component normally has.',
    ],
    types: [
      {name: 'Dependency confusion', description: 'Publishing a malicious public package with the same name as an internal private package, tricking a misconfigured build into pulling the public (malicious) one.'},
      {name: 'Typosquatting', description: 'Publishing a malicious package with a name one typo away from a popular legitimate one.'},
      {name: 'Compromised CI/CD pipeline', description: 'Gaining access to build infrastructure to inject malicious code during the build process itself, after review but before deployment.'},
      {name: 'Unsigned/tampered updates', description: 'An update mechanism that doesn\'t verify integrity, letting a man-in-the-middle or compromised distribution point serve a malicious update.'},
    ],
    defenses: ['Pin exact dependency versions and verify checksums/signatures', 'Use private package registries with scoped namespaces to prevent confusion attacks', 'Harden and audit CI/CD pipeline access as rigorously as production access', 'Require signed commits and signed releases where possible'],
  },
  'insecure-design': {
    title: 'Insecure Design',
    cwe: 'CWE-657',
    vaultWeakness: ['Violation of Secure Design Principles'],
    summary: 'A security weakness that exists because of how a feature was designed in the first place — not a coding bug, but a missing control that should have been part of the architecture from the start.',
    howItWorks: [
      'A feature is built to satisfy a business requirement without a threat model asking "how could this be abused?"',
      'A control that should exist by design — rate limiting, a business-logic constraint, server-side validation — is simply never planned for.',
      'The implementation is "correct" relative to its (incomplete) design — there\'s no coding bug to point at.',
      'An attacker uses the feature exactly as built, just in a way its designers didn\'t anticipate.',
    ],
    types: [
      {name: 'Missing rate limiting by design', description: 'A feature (like a discount-code checker) with no design-level limit on attempts, enabling automated abuse.'},
      {name: 'Trusting client-side validation', description: 'Validation logic that exists only in the frontend, with the assumption — never verified — that the backend doesn\'t need to repeat it.'},
      {name: 'Flawed business logic', description: 'A multi-step process (like checkout or a workflow approval) that can be reordered, repeated, or skipped in ways the design never accounted for.'},
    ],
    defenses: ['Threat-model features before building them, not after an incident', 'Treat the backend as the sole source of truth for validation, always', 'Design abuse cases (rate limits, sequencing, idempotency) into features from the start, not bolted on later'],
  },
  'business-logic-abuse': {
    title: 'Business Logic Abuse',
    vaultWeakness: ['Business Logic Errors'],
    summary: 'An attacker automates a legitimate feature at a scale or speed no human user would operate at, extracting value the business never intended to give away — without exploiting any traditional technical bug.',
    howItWorks: [
      'A business workflow exists for legitimate use (buying a limited item, creating an account, applying a promo code).',
      'The workflow has no meaningful limit on how fast or how many times it can be repeated.',
      'The attacker automates the workflow at scale, far beyond normal human usage patterns.',
      'The business absorbs the cost — lost inventory, fraudulent accounts, or abused promotions — with no "vulnerability" in the traditional sense to patch.',
    ],
    types: [
      {name: 'Scalping bots', description: 'Automating purchase of limited-availability items faster than real customers can, for resale.'},
      {name: 'Automated fake account creation', description: 'Mass-creating accounts to claim sign-up bonuses or evade per-account limits.'},
      {name: 'Bulk purchasing/promo abuse', description: 'Automating use of a promotional code or discount far beyond its intended per-customer scope.'},
    ],
    defenses: ['Rate limit and add friction (CAPTCHA, device fingerprinting) to sensitive business flows, not just login', 'Detect non-human usage patterns (speed, volume, timing) and challenge or block them', 'Design promotions and limited releases with abuse resistance in mind from the start'],
  },
  'rate-limiting-dos': {
    title: 'Lack of Rate Limiting / Resource Exhaustion',
    cwe: 'CWE-770',
    vaultWeakness: ['Uncontrolled Resource Consumption', 'Allocation of Resources Without Limits or Throttling'],
    summary: 'An endpoint has no meaningful limit on request volume, payload size, or expensive operations, letting an attacker degrade or deny service to legitimate users.',
    howItWorks: [
      'An endpoint performs some amount of work per request — a database query, a file operation, a computation.',
      'There\'s no cap on how often it can be called, how large its input can be, or how many results it can return at once.',
      'The attacker sends a high volume of requests, or requests deliberately designed to be expensive.',
      'Server resources (CPU, memory, database connections) are exhausted, degrading or denying service for everyone.',
    ],
    types: [
      {name: 'Request flooding', description: 'Simple high-volume request spam against an endpoint with no rate limit.'},
      {name: 'Large payload DoS', description: 'Submitting an oversized request body or file that consumes disproportionate resources to process.'},
      {name: 'Unbounded pagination/query abuse', description: 'Requesting an extremely large page size or unindexed query that forces an expensive database scan.'},
    ],
    defenses: ['Apply rate limits per user/IP/API key at the gateway level', 'Enforce maximum payload sizes and pagination limits server-side', 'Set query timeouts and resource quotas so one expensive request can\'t starve the whole system'],
  },
  'improper-inventory': {
    title: 'Improper Inventory Management',
    summary: 'Old, undocumented, or forgotten API versions and endpoints remain live and unmonitored, giving attackers a way in that the security team doesn\'t even know exists.',
    howItWorks: [
      'An API evolves over time — new versions ship, old ones are meant to be retired, internal-only endpoints get added for debugging.',
      'Deprecated versions or debug endpoints are never actually decommissioned, just no longer advertised.',
      'Because they\'re "forgotten," they don\'t receive the same security attention, patching, or monitoring as the current, documented surface.',
      'An attacker discovers them (via old documentation, JS bundles, or fuzzing) and targets the weaker, unmaintained version.',
    ],
    types: [
      {name: 'Zombie/shadow API versions', description: 'Old API versions left running in parallel with the current one, often with weaker security controls.'},
      {name: 'Undocumented endpoints', description: 'Debug or internal-only routes accidentally exposed and never inventoried.'},
      {name: 'Deprecated endpoint exposure', description: 'Endpoints marked deprecated in documentation but never actually disabled.'},
    ],
    defenses: ['Maintain a live, accurate inventory of every API version and endpoint in production', 'Actually decommission deprecated versions on a schedule, not just stop documenting them', 'Apply consistent monitoring and patching across all live versions, not just the current one'],
  },
  'logging-monitoring-failures': {
    title: 'Security Logging and Monitoring Failures',
    cwe: 'CWE-778',
    summary: 'Security-relevant events aren\'t logged, or logs exist but nobody watches or alerts on them, so breaches and abuse go undetected — often for a long time.',
    howItWorks: [
      'Sensitive actions (logins, failed auth attempts, privilege changes, data access) occur without generating a log entry, or logs exist but are never reviewed.',
      'An attacker\'s activity — brute forcing, data exfiltration, privilege abuse — produces no alert.',
      'The attack continues undetected, often for weeks or months, maximizing damage.',
      'Discovery finally happens externally (a customer complaint, a breach notification from elsewhere) rather than through internal detection.',
    ],
    types: [
      {name: 'Missing audit trails', description: 'No record at all of who did what, when — making incident investigation nearly impossible after the fact.'},
      {name: 'Alert fatigue', description: 'Logging exists, but generates so much noise that real alerts are lost among false positives.'},
      {name: 'Log injection', description: 'Attacker-controlled input written unsanitized into logs, letting them forge log entries or break log parsing.'},
    ],
    defenses: ['Log all security-relevant events: auth attempts, access control failures, privileged actions', 'Actually alert on and triage suspicious patterns in real time, not just store logs passively', 'Sanitize any user input before it\'s written into a log entry', 'Retain logs long enough to support real incident investigation'],
  },
  'prototype-pollution': {
    title: 'Prototype Pollution',
    cwe: 'CWE-1321',
    summary: 'In JavaScript, an attacker injects properties onto a shared base object (Object.prototype), affecting every object in the application that inherits from it — sometimes leading to logic bypass or code execution.',
    howItWorks: [
      'A JavaScript app merges or assigns user-controlled data into an object using a recursive merge/clone utility.',
      'The attacker includes a key like `__proto__` or `constructor.prototype` in their input.',
      'A naive merge function follows that key path and writes onto the shared prototype object itself, not the intended target object.',
      'Every object in the application that inherits from that prototype now carries the attacker\'s injected property, which can flip logic checks elsewhere in the app or, in some environments, lead to code execution.',
    ],
    types: [
      {name: 'Client-side pollution', description: 'Corrupting shared state in the browser, potentially enabling a secondary XSS.'},
      {name: 'Server-side pollution (Node.js)', description: 'The more severe case — polluting the prototype in a Node.js process can affect every request the server handles, and in some cases leads to remote code execution.'},
    ],
    code: {
      language: 'js',
      vulnerable: "function merge(target, source) {\n  for (const key in source) {\n    if (typeof source[key] === 'object') merge(target[key], source[key]);\n    else target[key] = source[key];\n  }\n}",
      fixed: "function merge(target, source) {\n  for (const key in source) {\n    if (key === '__proto__' || key === 'constructor') continue; // block dangerous keys\n    if (typeof source[key] === 'object') merge(target[key], source[key]);\n    else target[key] = source[key];\n  }\n}",
    },
    defenses: ['Use `Object.create(null)` or `Map` for objects built from user input, instead of plain object literals', 'Freeze `Object.prototype` in sensitive contexts', 'Use merge/clone libraries with known protections against `__proto__` keys, and keep them updated', 'Validate and sanitize keys in any recursive merge of user-controlled data'],
  },
  'exception-handling': {
    title: 'Mishandling of Exceptional Conditions',
    cwe: 'CWE-755',
    vaultWeakness: ['Information Exposure Through an Error Message'],
    summary: 'Errors, edge cases, and unexpected states aren\'t handled safely — leaking internal details, or worse, leaving the application in an insecure "fail-open" state instead of safely denying access.',
    howItWorks: [
      'An unexpected condition occurs — a malformed input, a downstream service timing out, an unhandled edge case in business logic.',
      'The application\'s error-handling path wasn\'t designed with security in mind — it either exposes internal details or takes the "safe for availability, unsafe for security" path.',
      'In the worst case, a check that fails to complete is treated as if it passed ("fail open") instead of denying by default.',
      'The attacker deliberately triggers the exceptional condition to get information, or to slip past a control that only runs on the "normal" path.',
    ],
    types: [
      {name: 'Verbose stack traces', description: 'Unhandled exceptions rendered directly to the user, revealing file paths, library versions, or query structure.'},
      {name: 'Fail-open error handling', description: 'A security check (like an authorization call) that, if it errors out, defaults to allowing access instead of denying it.'},
      {name: 'Unhandled edge cases enabling bypass', description: 'An input the developer never considered (empty, null, extremely large, wrong type) sends the code down a path where a security check is silently skipped.'},
    ],
    defenses: ['Fail closed by default — any error in a security check should deny, not allow', 'Return generic error messages to users; log full details server-side only', 'Explicitly test edge cases (empty, null, oversized, malformed input) as part of security testing, not just happy-path QA'],
  },

  // --- Smart contract ---
  reentrancy: {
    title: 'Reentrancy Attack',
    cwe: 'CWE-841',
    summary: 'A contract calls out to another (attacker-controlled) contract before finishing its own bookkeeping, letting the callee call straight back in and repeat an action using stale state.',
    howItWorks: [
      'A contract sends funds or calls another contract as part of a function, then updates its own internal balance/state afterward.',
      'The external call transfers control to the recipient contract before that state update happens.',
      'If the recipient is malicious, its fallback function immediately calls the original function again.',
      'Because the balance hasn\'t been updated yet, the check passes again, letting the attacker drain funds repeatedly in a single transaction.',
    ],
    types: [
      {name: 'Single-function reentrancy', description: 'The classic case — the same function is called back into repeatedly before its first execution finishes.'},
      {name: 'Cross-function reentrancy', description: 'The re-entrant call targets a different function that shares the same unprotected state.'},
      {name: 'Read-only reentrancy', description: 'A view function returns stale state during an in-progress external call, misleading another contract that reads it.'},
    ],
    code: {
      language: 'js',
      vulnerable: "// Solidity, simplified\nfunction withdraw(uint amount) public {\n  require(balances[msg.sender] >= amount);\n  (bool ok, ) = msg.sender.call{value: amount}(\"\");\n  require(ok);\n  balances[msg.sender] -= amount; // updated AFTER the external call\n}",
      fixed: "function withdraw(uint amount) public {\n  require(balances[msg.sender] >= amount);\n  balances[msg.sender] -= amount; // update state BEFORE the call\n  (bool ok, ) = msg.sender.call{value: amount}(\"\");\n  require(ok);\n}",
    },
    defenses: ['Follow checks-effects-interactions: update all state before making any external call', 'Use a reentrancy guard (mutex) modifier on functions that transfer value', 'Prefer pull-payment patterns over pushing funds directly to arbitrary addresses'],
  },
  'integer-overflow': {
    title: 'Integer Overflow / Underflow',
    cwe: 'CWE-190',
    summary: 'Arithmetic on a fixed-size integer exceeds its representable range and silently wraps around to a wildly different value, instead of raising an error.',
    howItWorks: [
      'A calculation adds to, subtracts from, or multiplies a fixed-size integer variable using attacker-influenced values.',
      'The true mathematical result falls outside the range that integer type can represent.',
      'Without an overflow check, the value silently wraps around (e.g. subtracting 1 from 0 on an unsigned integer produces the maximum possible value instead of an error).',
      'Downstream logic uses this wrapped value as if it were correct, often granting a huge unintended balance or bypassing a limit check.',
    ],
    types: [
      {name: 'Overflow', description: 'A value exceeds the maximum the type can hold and wraps back around to a small number.'},
      {name: 'Underflow', description: 'A value goes below zero on an unsigned type and wraps around to a very large number instead.'},
    ],
    defenses: ['Use a language/compiler version with built-in overflow checks (e.g. Solidity ≥0.8 reverts on overflow by default)', 'For earlier versions, use a vetted safe-math library for all arithmetic', 'Validate that user-supplied values fall within sane bounds before any calculation'],
  },
  'timestamp-dependence': {
    title: 'Timestamp Dependence',
    summary: 'Contract logic depends on the block timestamp for something security-sensitive, but the party producing a block has some latitude to influence that value.',
    howItWorks: [
      'A contract uses `block.timestamp` to make a security-relevant decision — a lottery draw, an unlock time, a randomness seed.',
      'The block producer can shift the timestamp within a small tolerance window without the block being rejected.',
      'If there\'s value at stake, a block producer (or someone colluding with one) is incentivized to nudge the timestamp toward a favorable outcome.',
      'The contract\'s "random" or time-gated decision is quietly biased in the attacker\'s favor.',
    ],
    types: [
      {name: 'Randomness seeding', description: 'Using the timestamp as entropy for something that\'s supposed to be unpredictable.'},
      {name: 'Time-lock manipulation', description: 'Nudging a timestamp-gated unlock or deadline slightly earlier or later than intended.'},
    ],
    defenses: ['Never use block.timestamp as a source of randomness', 'For time windows, tolerate the small manipulation margin explicitly in the design rather than assuming exact precision', 'Use a dedicated randomness oracle (like Chainlink VRF) instead of on-chain values for anything requiring real unpredictability'],
  },
  'smart-contract-access-control': {
    title: 'Smart Contract Access Control Vulnerabilities',
    cwe: 'CWE-284',
    summary: 'A contract\'s privileged functions (minting, withdrawing, upgrading, pausing) aren\'t properly restricted to the intended caller.',
    howItWorks: [
      'A contract defines a sensitive function — transferring ownership, minting tokens, draining a treasury.',
      'The function is missing an access-control modifier entirely, or uses a weak/incorrect check.',
      'A common mistake is checking `tx.origin` (the original transaction sender) instead of `msg.sender` (the immediate caller), which a malicious intermediate contract can exploit.',
      'Any caller — not just the intended owner or admin — can invoke the function directly.',
    ],
    types: [
      {name: 'Missing modifier', description: 'A sensitive function has no access restriction at all.'},
      {name: 'tx.origin authorization bypass', description: 'Checking tx.origin instead of msg.sender lets an attacker\'s contract trick a victim into unknowingly authorizing an action.'},
      {name: 'Misconfigured role assignment', description: 'Role-based access control is implemented but roles are granted too broadly or never revoked.'},
    ],
    code: {
      language: 'js',
      vulnerable: "// Solidity, simplified\nfunction withdrawAll() public {\n  require(tx.origin == owner); // wrong check\n  payable(msg.sender).transfer(address(this).balance);\n}",
      fixed: "function withdrawAll() public {\n  require(msg.sender == owner); // correct check\n  payable(msg.sender).transfer(address(this).balance);\n}",
    },
    defenses: ['Use msg.sender for authorization checks, never tx.origin', 'Apply well-tested access-control modifiers (e.g. OpenZeppelin\'s Ownable/AccessControl) rather than hand-rolling them', 'Audit every state-changing function for a missing or weak permission check'],
  },
  'front-running': {
    title: 'Front-Running Attack',
    summary: 'Because pending blockchain transactions are visible before they\'re confirmed, an attacker can see a profitable transaction and submit their own with a higher fee to have it processed first.',
    howItWorks: [
      'A transaction is broadcast to the network and sits in the public mempool waiting to be included in a block.',
      'An attacker (or automated bot) watches the mempool for transactions that will predictably move a price or trigger a payout.',
      'The attacker submits their own transaction with a higher gas fee, incentivizing miners/validators to include it first.',
      'The attacker\'s transaction executes ahead of the original, capturing the value the original transaction would have created.',
    ],
    types: [
      {name: 'Classic front-running', description: 'Copying a pending transaction\'s intent and racing to execute it first.'},
      {name: 'Sandwich attack', description: 'Placing one transaction immediately before and one immediately after a victim\'s trade, profiting from the price movement the victim\'s own trade causes.'},
    ],
    defenses: ['Use commit-reveal schemes so transaction intent isn\'t visible before execution', 'Set tight slippage tolerances on trades to limit how much a sandwich attack can extract', 'Consider private mempools or MEV-protected transaction relays for sensitive transactions'],
  },
  'gas-limit-dos': {
    title: 'Gas Limit / Unbounded Loop Denial of Service',
    cwe: 'CWE-400',
    summary: 'A contract operation — often a loop over an on-chain array that keeps growing — eventually costs more gas than a block can hold, permanently blocking that operation for everyone.',
    howItWorks: [
      'A contract function loops over a data structure (like a list of all depositors) whose size grows over time.',
      'Each iteration costs gas, and the total cost scales with the structure\'s size.',
      'Once the structure is large enough, the function\'s total gas cost exceeds the block gas limit.',
      'The function can never successfully complete again, effectively locking whatever it was supposed to do (like distributing payouts) forever.',
    ],
    types: [
      {name: 'Unbounded loop DoS', description: 'A loop with no size cap that grows until it\'s permanently unexecutable.'},
      {name: 'Griefing via forced gas cost', description: 'An attacker deliberately inflates a shared data structure (e.g. by making many tiny deposits) to push up everyone else\'s gas costs.'},
    ],
    defenses: ['Avoid loops over unbounded, attacker-influenced collections in on-chain functions', 'Use pull-payment patterns (each user withdraws their own funds) instead of push patterns that loop over everyone', 'Paginate any necessary batch operation across multiple transactions'],
  },
  'insecure-randomness': {
    title: 'Insecure Randomness (On-Chain)',
    cwe: 'CWE-330',
    summary: 'A blockchain is deterministic by design, so sourcing "randomness" from on-chain values an attacker can predict, observe, or influence isn\'t actually random.',
    howItWorks: [
      'A contract needs unpredictability for something like a lottery draw or loot distribution.',
      'It derives that value from on-chain data — a block hash, timestamp, or similar — that all participants can also see.',
      'A miner/validator, or anyone monitoring the mempool, can compute the same "random" outcome before committing to a transaction.',
      'They act only when the outcome favors them, or in some cases directly influence the value used.',
    ],
    types: [
      {name: 'Blockhash-based randomness', description: 'Using a recent block hash as a seed, which is visible to everyone once mined and to block producers before that.'},
      {name: 'Timestamp-based randomness', description: 'Deriving randomness from block.timestamp, which a block producer has some ability to adjust.'},
    ],
    defenses: ['Use a dedicated verifiable-randomness oracle (e.g. Chainlink VRF) instead of any on-chain value', 'Never let a single party (including the contract deployer) be able to predict or bias the outcome', 'Where possible, commit to a choice before the random value is revealed (commit-reveal)'],
  },
  'unchecked-external-calls': {
    title: 'Unchecked External Calls',
    cwe: 'CWE-252',
    summary: 'A contract calls another contract or sends value, but doesn\'t check whether that call actually succeeded — silently treating a failure as if it worked.',
    howItWorks: [
      'A contract makes a low-level call (like `.call()` or `.send()`) to another address, which returns a success/failure flag instead of reverting automatically on failure.',
      'The calling code doesn\'t check that returned flag.',
      'If the external call fails — because the recipient rejects it, runs out of gas, or doesn\'t exist — execution continues anyway.',
      'The contract\'s internal state ends up inconsistent with reality: it believes a transfer or action succeeded when it didn\'t.',
    ],
    types: [
      {name: 'Unchecked low-level call', description: 'Ignoring the boolean return value of `.call()`/`.send()`.'},
      {name: 'Silent failure in a loop', description: 'One failed call inside a batch operation is skipped rather than handled, corrupting the batch\'s accounting.'},
    ],
    defenses: ['Always check the return value of any low-level external call and revert or handle failure explicitly', 'Prefer higher-level call patterns that revert automatically on failure where available', 'Use the checks-effects-interactions pattern so a failed call can\'t leave state half-updated'],
  },
  'price-oracle-manipulation': {
    title: 'Price Oracle Manipulation',
    summary: 'A contract trusts an external price feed to value assets, but that feed can itself be manipulated — often within a single transaction — skewing every calculation built on top of it.',
    howItWorks: [
      'A DeFi contract needs to know an asset\'s current price to calculate collateral ratios, swap rates, or liquidations.',
      'It reads that price from a source that reflects a single pool\'s current, momentary state (a "spot price") rather than a manipulation-resistant aggregate.',
      'An attacker temporarily distorts that pool\'s balance — often using a flash loan for capital — pushing the reported price far from its real value.',
      'The contract executes its logic using the distorted price, letting the attacker borrow more, pay less, or trigger unwarranted liquidations before the price reverts.',
    ],
    types: [
      {name: 'Spot-price manipulation', description: 'Directly skewing a single liquidity pool\'s momentary price via a large, temporary trade.'},
      {name: 'Flash-loan-funded manipulation', description: 'Using a flash loan\'s uncollateralized capital to make the price swing large enough to matter, then reverting it after profiting.'},
    ],
    defenses: ['Use time-weighted average prices (TWAP) over a meaningful window instead of instantaneous spot prices', 'Source prices from multiple independent oracles and cross-check them', 'Add sanity bounds that reject a price update that moves implausibly far in one block'],
  },
  'flash-loan-attack': {
    title: 'Flash Loan Attack',
    summary: 'An attacker borrows a very large, entirely uncollateralized sum for the duration of a single transaction, uses it to briefly distort a protocol\'s state, profits from that distortion, then repays the loan before the transaction ends.',
    howItWorks: [
      'A flash loan lets anyone borrow any amount, with the sole condition that it\'s repaid by the end of the same transaction — otherwise the whole transaction reverts as if it never happened.',
      'The attacker borrows an enormous sum with no collateral of their own.',
      'That capital is used to briefly manipulate a price, drain a pool\'s liquidity, or pass a large-balance check somewhere in the target protocol.',
      'The attacker extracts profit from that manipulation, repays the flash loan, and keeps the difference — all within one atomic transaction.',
    ],
    types: [
      {name: 'Price manipulation via flash loan', description: 'Using borrowed capital to distort a price oracle, then exploiting contracts that trust it.'},
      {name: 'Governance manipulation via flash loan', description: 'Temporarily acquiring enough governance tokens to pass a malicious proposal within one transaction.'},
    ],
    defenses: ['Don\'t rely on any single-transaction balance or price snapshot for critical decisions', 'Use TWAP pricing and multi-block confirmation for governance-weight calculations', 'Add explicit flash-loan detection/rate-limits where the protocol\'s design allows it'],
  },
  'arithmetic-precision-errors': {
    title: 'Arithmetic Errors (Rounding & Precision)',
    summary: 'Fixed-point math used to represent fractional values loses precision or rounds in the wrong direction, and an attacker who can trigger the calculation repeatedly profits from the accumulated error.',
    howItWorks: [
      'A contract represents fractional amounts (like shares of a pool) using integer math, since blockchains don\'t have native floating-point numbers.',
      'A division or ratio calculation rounds a result, and the code doesn\'t consistently round in the safe direction (e.g. always in the protocol\'s favor, never the user\'s).',
      'An attacker repeats a small transaction many times, each time capturing a tiny rounding benefit.',
      'Over enough repetitions, the accumulated rounding error becomes a meaningful, extractable profit.',
    ],
    types: [
      {name: 'Rounding direction exploit', description: 'Consistently rounding in the caller\'s favor instead of the protocol\'s, exploitable via repetition.'},
      {name: 'Precision loss in division', description: 'Dividing before multiplying (or similar ordering mistakes) that discards meaningful precision.'},
    ],
    defenses: ['Always round in favor of the protocol/pool, never the individual caller, for any ambiguous division', 'Multiply before dividing wherever mathematically valid, to preserve precision', 'Use well-audited fixed-point math libraries rather than hand-rolled division'],
  },
  'proxy-upgradeability': {
    title: 'Proxy & Upgradeability Vulnerabilities',
    summary: 'Upgradeable contracts route every call through a lightweight proxy that delegates to a separate logic contract; mismatched storage layouts or unprotected upgrade functions between versions can corrupt state or hand control to an attacker.',
    howItWorks: [
      'A proxy contract holds the actual state (storage) and forwards every call via `delegatecall` to a separate logic contract, which can be swapped out to "upgrade" the system.',
      'The proxy and each logic version must agree exactly on how storage slots are laid out.',
      'If a new logic version changes that layout, or the upgrade function itself isn\'t properly restricted, storage can be corrupted or an attacker can point the proxy at a malicious logic contract.',
      'Every user interaction now runs through the corrupted or malicious logic while still believing they\'re using the trusted proxy address.',
    ],
    types: [
      {name: 'Storage layout collision', description: 'A new implementation\'s variables don\'t line up with the proxy\'s existing storage slots, corrupting data.'},
      {name: 'Unprotected upgrade function', description: 'The function that points the proxy at a new logic contract lacks proper access control.'},
      {name: 'Uninitialized proxy', description: 'A newly deployed proxy or implementation is left uninitialized, letting an attacker call the initializer themselves and seize admin rights.'},
    ],
    defenses: ['Use well-audited proxy patterns (e.g. OpenZeppelin\'s upgradeable contracts) rather than a custom implementation', 'Strictly control and time-lock upgrade functions', 'Always disable initializers on the implementation contract itself, and verify storage layout compatibility before every upgrade'],
  },

  // --- Mobile ---
  'improper-platform-usage': {
    title: 'Improper Platform Usage',
    summary: 'A mobile OS provides security-relevant features — permission models, secure storage APIs, inter-app communication — and the app misuses or bypasses them instead of relying on them correctly.',
    howItWorks: [
      'The mobile platform (iOS/Android) exposes a secure, intended way to do something — request a permission, pass data between components, store a secret.',
      'The app either ignores that mechanism, uses it incorrectly, or requests far more access than it needs.',
      'That gap between "how it should be done" and "how the app actually does it" creates an opening.',
      'Another app, or an attacker with device access, exploits the misuse rather than any bug in the platform itself.',
    ],
    types: [
      {name: 'Insecure intent handling (Android)', description: 'An exported component accepts data from any other app without validating the sender or the data.'},
      {name: 'Misused platform permissions', description: 'Requesting broader permissions than the feature actually needs, expanding the impact if the app is compromised.'},
    ],
    defenses: ['Request the minimum permissions actually required, and explain why to users', 'Mark inter-app components as non-exported unless intentionally public, and validate any input they do accept', 'Use the platform\'s intended secure-storage and IPC mechanisms rather than custom equivalents'],
  },
  'mobile-insecure-data-storage': {
    title: 'Insecure Data Storage (Mobile)',
    cwe: 'CWE-922',
    summary: 'Sensitive data is stored on the device in a form that another app, a backup, or anyone with brief physical access can read.',
    howItWorks: [
      'The app stores sensitive data locally — credentials, tokens, personal data — for offline use or performance.',
      'That data is written to a local database, file, or log without encryption, or with encryption using a key that\'s just as easily accessible.',
      'Anyone with access to the device\'s filesystem (via a backup, a rooted/jailbroken device, or malware) can read it directly.',
      'The data is exposed just as if there had been no protection at all.',
    ],
    types: [
      {name: 'Unencrypted local database', description: 'Sensitive fields stored in plaintext in a local SQLite/Realm database.'},
      {name: 'Sensitive data in logs', description: 'Debug logging accidentally includes tokens, passwords, or personal data, which can persist in system logs.'},
    ],
    defenses: ['Use the platform\'s secure storage (Keychain on iOS, Keystore-backed encryption on Android) for anything sensitive', 'Never log secrets, even at debug level, in production builds', 'Exclude sensitive local data from device backups where the platform allows it'],
  },
  'mobile-insecure-communication': {
    title: 'Insecure Communication (Mobile)',
    cwe: 'CWE-319',
    summary: 'Data traveling between the app and its backend isn\'t adequately protected against interception or tampering, often because a control that should always be on is optional or absent.',
    howItWorks: [
      'The app communicates with a backend server over the network.',
      'Either the connection isn\'t enforced to use TLS everywhere, or it accepts any certificate rather than verifying the server\'s identity strictly.',
      'An attacker positioned on the network (public Wi-Fi, a compromised router) intercepts the traffic.',
      'Without certificate pinning or strict validation, the attacker can read or modify traffic that appears legitimate to the app.',
    ],
    types: [
      {name: 'Missing certificate pinning', description: 'The app trusts any certificate signed by any recognized authority, not specifically its own backend\'s certificate.'},
      {name: 'Cleartext transmission', description: 'Some requests fall back to plain HTTP, especially for "less sensitive" endpoints that still leak useful data.'},
    ],
    defenses: ['Enforce TLS for every network request, with no cleartext fallback', 'Implement certificate or public-key pinning for connections to your own backend', 'Fail closed on certificate validation errors rather than prompting the user to "continue anyway"'],
  },
  'mobile-insecure-auth': {
    title: 'Insecure Authentication (Mobile)',
    summary: 'The app\'s login or local-unlock mechanism has weaknesses specific to running on a device the user (or an attacker with the device) physically controls.',
    howItWorks: [
      'The app implements authentication — a password login, PIN, or biometric unlock — to protect access to the account or app itself.',
      'The check is implemented client-side without proper backend enforcement, or the biometric/PIN gate can be bypassed by manipulating the app\'s local state.',
      'An attacker with physical access to an unlocked or compromised device manipulates the client to skip the check.',
      'They reach an authenticated state without ever providing valid credentials.',
    ],
    types: [
      {name: 'Biometric bypass', description: 'A biometric prompt guards a client-side flag rather than being cryptographically tied to actually unlocking a secret.'},
      {name: 'Client-side-only session checks', description: 'The app decides "logged in or not" locally, without the backend re-verifying on each sensitive request.'},
    ],
    defenses: ['Tie biometric unlock to releasing an actual cryptographic key, not just setting a boolean flag', 'Re-verify authentication state server-side for every sensitive action, not just at app launch', 'Treat the device as untrusted — assume an attacker may have full control of the client'],
  },
  'client-code-quality': {
    title: 'Client Code Quality Issues',
    summary: 'Ordinary coding bugs — buffer overflows, format string issues, memory-safety mistakes — that are exploitable specifically because the code runs on a device an attacker can fully control and inspect.',
    howItWorks: [
      'The app includes native code (C/C++, or unsafe code in another language) for performance or platform integration.',
      'That code has a classic memory-safety bug: a buffer overflow, an unchecked array index, a format string vulnerability.',
      'On a server, such a bug might only be reachable remotely in limited ways. On a device an attacker owns, they can feed it arbitrary crafted input directly.',
      'The bug is triggered locally, potentially leading to a crash or code execution within the app\'s sandbox.',
    ],
    types: [
      {name: 'Buffer overflow in native code', description: 'Writing past the end of a fixed-size buffer in a native library the app bundles.'},
      {name: 'Unsafe memory handling', description: 'Use-after-free or similar memory-safety issues in native components.'},
    ],
    defenses: ['Prefer memory-safe languages for new native components where possible', 'Fuzz-test any native code that parses untrusted input (files, network responses)', 'Enable platform memory-protection features (ASLR, stack canaries) at build time'],
  },
  'code-tampering': {
    title: 'Code Tampering',
    cwe: 'CWE-494',
    summary: 'Since a mobile app ships as a file the user\'s device fully controls, an attacker can modify its binary or resources and redistribute the tampered version.',
    howItWorks: [
      'An attacker obtains the app\'s installable package (APK/IPA).',
      'They decompile or patch it — removing license checks, injecting ads or malware, or altering its behavior.',
      'The tampered app is repackaged and distributed through unofficial channels, or side-loaded onto a device.',
      'Users who install the tampered version run code the original developer never intended, often without any obvious sign it\'s been modified.',
    ],
    types: [
      {name: 'Repackaging attacks', description: 'Decompiling, modifying, and redistributing an app under the same or a similar identity.'},
      {name: 'Runtime patching', description: 'Using a hooking framework to modify the app\'s behavior at runtime without altering the installed package itself.'},
    ],
    defenses: ['Implement runtime integrity checks that detect a modified binary or resources', 'Use code signing and verify it, since a tampered app requires re-signing with a different, untrusted key', 'Add root/jailbreak and hooking-framework detection for security-sensitive apps'],
  },
  'reverse-engineering': {
    title: 'Reverse Engineering',
    summary: 'An attacker decompiles the app\'s binary to recover source-level logic, embedded secrets, or algorithms the developers assumed nobody could read.',
    howItWorks: [
      'The app ships as a compiled binary, which the attacker has unrestricted access to once it\'s installed on any device.',
      'Using decompilation and disassembly tools, the attacker recovers logic that closely resembles the original source code, especially for managed-runtime languages.',
      'Any secret, algorithm, or business logic that was "hidden" only by being compiled is now fully visible.',
      'The attacker uses that insight to find further vulnerabilities, extract embedded keys, or clone proprietary functionality.',
    ],
    types: [
      {name: 'Binary decompilation', description: 'Converting compiled code back into readable, close-to-source logic.'},
      {name: 'String/resource extraction', description: 'Pulling hardcoded secrets, URLs, or debug strings directly out of the compiled package.'},
    ],
    defenses: ['Never rely on compiled code as a place to hide secrets — assume it will be read', 'Use code obfuscation to raise the cost of analysis, understanding it\'s a speed bump, not a real barrier', 'Keep genuinely sensitive logic and secrets server-side, not in the client at all'],
  },
  'extraneous-functionality': {
    title: 'Extraneous Functionality',
    cwe: 'CWE-489',
    summary: 'Hidden test code, debug backdoors, or internal-only features are accidentally left in the production build a user actually installs.',
    howItWorks: [
      'During development, engineers add debug menus, test accounts, or internal API endpoints for convenience.',
      'That functionality is meant to be stripped or disabled before release, but the process for doing so is manual or incomplete.',
      'The shipped production app still contains the hidden functionality.',
      'An attacker who discovers it (via reverse engineering or a leaked internal build) gets access to capabilities never meant to be public.',
    ],
    types: [
      {name: 'Hidden backdoor functionality', description: 'A debug menu or master credential left reachable in the shipped app.'},
      {name: 'Internal-only endpoints', description: 'Backend routes intended only for internal testing, still callable by the production app or discoverable within it.'},
    ],
    defenses: ['Automate stripping of debug/test code as part of the release build pipeline, not a manual checklist step', 'Audit release builds specifically for leftover debug functionality before publishing', 'Never ship hardcoded test credentials or master overrides, even temporarily'],
  },
  'improper-credential-usage': {
    title: 'Improper Credential Usage',
    summary: 'API keys, tokens, or other credentials the app needs are hardcoded into the binary or otherwise mishandled at runtime, making them recoverable by anyone who inspects the app.',
    howItWorks: [
      'The app needs a credential to talk to a backend service or third-party API.',
      'Rather than obtaining it dynamically or storing it server-side, the credential is embedded directly in the app\'s source or configuration, compiled into the shipped binary.',
      'Anyone who decompiles the app or inspects its resources can extract the credential directly.',
      'The extracted credential is reused to impersonate the app, access the backing service directly, or run up costs on a shared API key.',
    ],
    types: [
      {name: 'Hardcoded API keys/secrets', description: 'Credentials embedded directly in source code or resource files.'},
      {name: 'Credentials in local storage', description: 'Tokens cached insecurely on-device after login, readable by other apps or with device access.'},
    ],
    defenses: ['Never embed long-lived secrets in a client app — proxy third-party API calls through your own backend instead', 'Use short-lived, scoped tokens issued per-session rather than static keys', 'Store any credential that must live on-device in the platform\'s secure storage, not plain preferences/files'],
  },
  'insufficient-io-validation': {
    title: 'Insufficient Input/Output Validation',
    summary: 'Data entering or leaving an application — a mobile client or a smart contract alike — isn\'t validated, letting malformed or malicious values reach logic that assumes clean input.',
    howItWorks: [
      'A function accepts a value (a form field, a deep-link parameter, a contract function argument) without checking its type, range, or format.',
      'An attacker supplies a value outside what the developer implicitly assumed — negative where only positive made sense, oversized, or in an unexpected format.',
      'Downstream logic, written assuming "normal" input, behaves unpredictably: a crash, a bypassed check, or an exploitable calculation.',
      'The lack of a validation gate at the boundary is the root cause, not any single downstream bug.',
    ],
    types: [
      {name: 'Client-side injection (mobile)', description: 'Unvalidated input reaching a local database query or WebView, enabling injection within the app itself.'},
      {name: 'Unvalidated contract parameters', description: 'A smart contract function argument used directly in a calculation or transfer without range/sanity checks.'},
    ],
    defenses: ['Validate every input at the boundary where it enters the system, not just deep inside business logic', 'Use an explicit allowlist of acceptable values/ranges rather than trying to blocklist bad ones', 'Fail closed — reject anything that doesn\'t clearly match the expected shape'],
  },
  'inadequate-privacy-controls': {
    title: 'Inadequate Privacy Controls',
    summary: 'The app collects, stores, or shares more personal data than it discloses to the user, or fails to actually honor the privacy choices a user makes.',
    howItWorks: [
      'The app requests access to data (location, contacts, device identifiers) beyond what a feature genuinely requires.',
      'That data is collected, and sometimes shared with third-party SDKs (analytics, ads) bundled into the app.',
      'Privacy settings a user configures — opting out of tracking, for instance — aren\'t consistently enforced across every code path and bundled SDK.',
      'Personal data ends up collected, retained, or shared in ways the user never actually agreed to.',
    ],
    types: [
      {name: 'Excessive data collection', description: 'Gathering more personal data than the stated feature set requires.'},
      {name: 'Third-party SDK leakage', description: 'Bundled analytics or ad SDKs transmit personal data independently of the app\'s own privacy controls.'},
    ],
    defenses: ['Collect only the data a feature genuinely needs, and state clearly why', 'Audit every bundled third-party SDK for what data it collects and where it sends it', 'Ensure privacy opt-outs are enforced consistently across the app and all embedded SDKs, not just the primary UI'],
  },
  'insufficient-binary-protection': {
    title: 'Insufficient Binary Protections',
    summary: 'The compiled app lacks defenses — obfuscation, integrity self-checks, anti-debugging — against being tampered with or reverse engineered, leaving Code Tampering and Reverse Engineering easier than they need to be.',
    howItWorks: [
      'A shipped app is, by default, just a file an attacker can freely inspect, decompile, and modify.',
      'Without additional protections, there\'s nothing raising the cost of doing so beyond the platform\'s baseline.',
      'An attacker uses standard, freely available tooling to decompile, patch, or attach a debugger to the running app with little friction.',
      'This isn\'t a vulnerability in itself so much as the absence of controls that would have made the app a harder, less worthwhile target.',
    ],
    types: [
      {name: 'Missing anti-tampering checks', description: 'No runtime verification that the app\'s own code or resources match what was originally signed.'},
      {name: 'Missing anti-debugging', description: 'No detection or resistance to a debugger being attached to the running app.'},
    ],
    defenses: ['Add runtime integrity checks that detect binary or resource modification', 'Add anti-debugging and root/jailbreak detection proportional to the app\'s actual risk (a banking app needs more than a casual game)', 'Treat these as a cost-raising layer, not a substitute for not putting real secrets in the client at all'],
  },
};

// Maps every chip label that appears anywhere in AttackAtlas/data.js to a
// canonical technique above. Kept as an explicit table (rather than fuzzy
// matching) so coverage is easy to audit and extend.
export const ALIASES = {
  'SQL Injection': 'sql-injection',
  'SQL Injection via API Params': 'sql-injection',
  'Command Injection': 'command-injection',
  'OS Command Injection': 'command-injection',
  'LDAP Injection': 'ldap-injection',
  'XPath Injection': 'xpath-injection',
  'NoSQL Injection': 'nosql-injection',
  'Cross-Site Scripting': 'xss',
  'Reflected XSS': 'xss',
  'Stored XSS': 'xss',
  'DOM-based XSS': 'xss',
  'Mutation XSS': 'xss',
  IDOR: 'idor',
  'IDOR via API': 'idor',
  'Object ID Enumeration': 'idor',
  'Privilege Escalation': 'privilege-escalation',
  'Horizontal Privilege Escalation': 'privilege-escalation',
  'Vertical Privilege Escalation': 'privilege-escalation',
  'Admin Endpoint Access as Regular User': 'privilege-escalation',
  'CORS Misconfiguration': 'cors-misconfig',
  'Verbose CORS': 'cors-misconfig',
  'Forced Browsing': 'forced-browsing',
  'Server-Side Request Forgery': 'ssrf',
  'Blind SSRF': 'ssrf',
  'Cloud Metadata Endpoint Access': 'ssrf',
  'Cloud Metadata Access via API': 'ssrf',
  'Internal Port Scanning via SSRF': 'ssrf',
  'Internal Network Pivoting': 'ssrf',
  'XXE-based SSRF': 'ssrf',
  'SSRF via Chained APIs': 'ssrf',
  'XXE File Disclosure': 'xxe',
  'Billion Laughs (XML Bomb)': 'xxe',
  'Blind XXE via OOB Channel': 'xxe',
  'Insecure Deserialization': 'insecure-deserialization',
  'Java Deserialization RCE': 'insecure-deserialization',
  'PHP Object Injection': 'insecure-deserialization',
  'Python Pickle Exploitation': 'insecure-deserialization',
  'Credential Stuffing': 'credential-stuffing',
  'Brute Force': 'brute-force',
  'Brute Force via Unlimited Requests': 'brute-force',
  'Silent Brute-Force': 'brute-force',
  'Session Fixation': 'session-attacks',
  'Session ID in URL': 'session-attacks',
  'Weak Session Tokens': 'session-attacks',
  'Weak Password Recovery': 'password-recovery',
  'MFA Bypass': 'mfa-bypass',
  'JWT Tampering': 'jwt-attacks',
  'JWT "none" Algorithm Attack': 'jwt-attacks',
  'Token Replay': 'jwt-attacks',
  'Weak API Keys': 'jwt-attacks',
  'Cleartext Storage': 'cryptographic-failures',
  'Weak Encryption Algorithms': 'cryptographic-failures',
  'Missing TLS': 'cryptographic-failures',
  'Missing Encryption at Rest': 'cryptographic-failures',
  'Weak Password Hashing': 'cryptographic-failures',
  'Weak Password Hashing (MD5/SHA1)': 'cryptographic-failures',
  'Hardcoded Keys': 'cryptographic-failures',
  'Hardcoded Secrets': 'cryptographic-failures',
  'Downgrade Attacks': 'cryptographic-failures',
  'Mass Assignment': 'mass-assignment',
  'Overposting Hidden Fields': 'mass-assignment',
  'Role Field Injection via Request Body': 'mass-assignment',
  'Sensitive Property Exposure': 'mass-assignment',
  'Over-fetching in Responses': 'mass-assignment',
  'Unfiltered Sensitive Fields': 'mass-assignment',
  'Data Injection from Upstream APIs': 'mass-assignment',
  'Trusting Third-Party Responses Blindly': 'mass-assignment',
  'Default Credentials': 'security-misconfiguration',
  'Default Configs': 'security-misconfiguration',
  'Verbose Error Messages': 'security-misconfiguration',
  'Verbose Errors': 'security-misconfiguration',
  'Verbose Error Bodies': 'security-misconfiguration',
  'Unnecessary Features Enabled': 'security-misconfiguration',
  'Unnecessary HTTP Methods': 'security-misconfiguration',
  'Unnecessary HTTP Methods Enabled': 'security-misconfiguration',
  'Missing Security Headers': 'security-misconfiguration',
  'Exposed Debug Endpoints': 'security-misconfiguration',
  'Exposed Backup Files': 'security-misconfiguration',
  'Open Cloud Storage Buckets': 'security-misconfiguration',
  'Misconfigured Cloud Storage': 'security-misconfiguration',
  'Known-CVE Library Exploitation': 'vulnerable-components',
  'Unpatched Software': 'vulnerable-components',
  'Unpatched CMS Plugins': 'vulnerable-components',
  'Outdated Framework Exploits': 'vulnerable-components',
  'Unsupported Software': 'vulnerable-components',
  'Dependency Confusion': 'supply-chain',
  'Malicious npm/PyPI Packages': 'supply-chain',
  'Compromised CI/CD Pipelines': 'supply-chain',
  Typosquatting: 'supply-chain',
  'CI/CD Pipeline Poisoning': 'supply-chain',
  'Unsigned Software Updates': 'supply-chain',
  'Unsigned Updates': 'supply-chain',
  'Trusting Client-Side Validation': 'insecure-design',
  'Flawed Business Logic': 'insecure-design',
  'Missing Threat Modeling': 'insecure-design',
  'Missing Rate Limiting by Design': 'insecure-design',
  'Scalping Bots': 'business-logic-abuse',
  'Automated Fake Account Creation': 'business-logic-abuse',
  'Bulk Purchasing Abuse': 'business-logic-abuse',
  'API Flooding': 'rate-limiting-dos',
  'Resource Exhaustion': 'rate-limiting-dos',
  'Large Payload DoS': 'rate-limiting-dos',
  'Unbounded Pagination Abuse': 'rate-limiting-dos',
  'Zombie/Shadow API Versions': 'improper-inventory',
  'Undocumented Endpoints': 'improper-inventory',
  'Deprecated Endpoint Exposure': 'improper-inventory',
  'Undetected Breaches': 'logging-monitoring-failures',
  'Missing Audit Trails': 'logging-monitoring-failures',
  'Log Injection': 'logging-monitoring-failures',
  'Missing Alerting on Auth Failures': 'logging-monitoring-failures',
  'Missing Rate-Limit Alerts': 'logging-monitoring-failures',
  'Undetected API Abuse': 'logging-monitoring-failures',
  'Undetected Data Exfiltration': 'logging-monitoring-failures',
  'Alert Fatigue': 'logging-monitoring-failures',
  'Fail-Open Error Handling': 'exception-handling',
  'Unhandled Edge Cases Enabling Bypass': 'exception-handling',
  'Verbose Stack Traces': 'exception-handling',
  'Prototype Pollution': 'prototype-pollution',

  // Smart contract
  'Reentrancy Attack': 'reentrancy',
  'Cross-Function Reentrancy': 'reentrancy',
  'Integer Overflow': 'integer-overflow',
  'Integer Underflow': 'integer-overflow',
  'Timestamp Dependence': 'timestamp-dependence',
  'Block Timestamp Manipulation': 'timestamp-dependence',
  'Missing Access Control Modifier': 'smart-contract-access-control',
  'tx.origin Authorization Bypass': 'smart-contract-access-control',
  'Front-Running Attack': 'front-running',
  'MEV Sandwich Attack': 'front-running',
  'Gas Limit DoS': 'gas-limit-dos',
  'Unbounded Loop DoS': 'gas-limit-dos',
  'Predictable Randomness': 'insecure-randomness',
  'Blockhash-based Randomness Exploit': 'insecure-randomness',
  'Unchecked External Calls': 'unchecked-external-calls',
  'Unchecked Call Return Value': 'unchecked-external-calls',
  'Price Oracle Manipulation': 'price-oracle-manipulation',
  'Flash Loan Price Manipulation': 'price-oracle-manipulation',
  'Flash Loan Attack': 'flash-loan-attack',
  'Rounding Direction Exploit': 'arithmetic-precision-errors',
  'Precision Loss in Division': 'arithmetic-precision-errors',
  'Storage Layout Collision': 'proxy-upgradeability',
  'Unprotected Upgrade Function': 'proxy-upgradeability',

  // Mobile
  'Improper Platform Usage': 'improper-platform-usage',
  'Insecure Intent Handling': 'improper-platform-usage',
  'Misused Platform Permissions': 'improper-platform-usage',
  'Insecure Data Storage': 'mobile-insecure-data-storage',
  'Unencrypted Local Database': 'mobile-insecure-data-storage',
  'Sensitive Data in Logs': 'mobile-insecure-data-storage',
  'Insecure Communication': 'mobile-insecure-communication',
  'Missing Certificate Pinning': 'mobile-insecure-communication',
  'Cleartext Transmission': 'mobile-insecure-communication',
  'Insecure Authentication': 'mobile-insecure-auth',
  'Biometric Bypass': 'mobile-insecure-auth',
  'Insecure Authorization': 'privilege-escalation',
  'Client Code Quality': 'client-code-quality',
  'Buffer Overflow in Native Code': 'client-code-quality',
  'Code Tampering': 'code-tampering',
  'Repackaging Attacks': 'code-tampering',
  'Reverse Engineering': 'reverse-engineering',
  'Binary Decompilation': 'reverse-engineering',
  'Extraneous Functionality': 'extraneous-functionality',
  'Hidden Backdoor Functionality': 'extraneous-functionality',
  'Improper Credential Usage': 'improper-credential-usage',
  'Insufficient Input/Output Validation': 'insufficient-io-validation',
  'Client Side Injection': 'insufficient-io-validation',
  'Inadequate Privacy Controls': 'inadequate-privacy-controls',
  'Excessive Data Collection': 'inadequate-privacy-controls',
  'Insufficient Binary Protections': 'insufficient-binary-protection',
  'Anti-Tampering Bypass': 'insufficient-binary-protection',
};

export function getTechniqueForLabel(label) {
  const id = ALIASES[label];
  return id ? {id, ...TECHNIQUES[id]} : null;
}
export function getTechniqueById(id) {
  return TECHNIQUES[id] ? {id, ...TECHNIQUES[id]} : null;
}
