const resources = [
  {
    name: 'TryHackMe',
    url: 'https://tryhackme.com/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Beginner-friendly, browser-based hacking rooms with guided walkthroughs across most security topics.',
  },
  {
    name: 'Hack The Box',
    url: 'https://www.hackthebox.com/',
    category: 'CTF Platforms',
    level: 'Advanced',
    description: 'Community-driven platform with retired/active vulnerable machines, from beginner to advanced.',
  },
  {
    name: 'Hack The Box Academy',
    url: 'https://academy.hackthebox.com/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'HTB\'s structured, guided courses — the on-ramp before jumping into HTB\'s sink-or-swim main labs.',
  },
  {
    name: 'HackThisSite',
    url: 'https://www.hackthissite.org/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Long-running free training ground focused primarily on web exploitation challenges.',
  },
  {
    name: 'HackingHub',
    url: 'https://www.hackinghub.io/',
    category: 'CTF Platforms',
    level: 'Intermediate',
    description: 'Isolated, real-world web app/API labs and courses built from actual bug bounty and pentest findings.',
  },
  {
    name: 'CyberSecLabs',
    url: 'https://www.cyberseclabs.co.uk/',
    category: 'CTF Platforms',
    level: 'Intermediate',
    description: 'Hands-on cybersecurity challenges and labs for practical skill-building.',
  },
  {
    name: 'VulnHub',
    url: 'https://www.vulnhub.com/',
    category: 'CTF Platforms',
    level: 'Intermediate',
    description: 'Free, downloadable vulnerable virtual machines to practice offline in your own lab.',
  },
  {
    name: 'OverTheWire',
    url: 'https://overthewire.org/wargames/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Classic wargames teaching security concepts through SSH-accessible challenge levels.',
  },
  {
    name: 'PicoCTF',
    url: 'https://picoctf.org/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Beginner-oriented computer security education program with a large always-available challenge set.',
  },
  {
    name: 'pwn.college',
    url: 'https://pwn.college/',
    category: 'CTF Platforms',
    level: 'Advanced',
    description: 'University-grade binary exploitation and systems security curriculum, organized into "dojos."',
  },
  {
    name: 'WebSec',
    url: 'https://websec.fr/',
    category: 'CTF Platforms',
    level: 'Intermediate',
    description: 'Web-based CTF challenges focused on application security.',
  },
  {
    name: 'Pwn.tn',
    url: 'https://pwn.tn/',
    category: 'CTF Platforms',
    level: 'Intermediate',
    description: 'IT security challenges for fun and learning.',
  },
  {
    name: 'Root-Me',
    url: 'https://www.root-me.org/',
    category: 'CTF Platforms',
    level: 'Intermediate',
    description: 'Large, long-established library of hacking challenges across many categories.',
  },
  {
    name: 'CTFlearn',
    url: 'https://ctflearn.com/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Free platform with challenges for beginners through advanced CTF players.',
  },
  {
    name: 'Avatao',
    url: 'https://avatao.com/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Practical, scenario-based challenges for building cybersecurity skills.',
  },
  {
    name: 'Hacker101 CTF',
    url: 'https://ctf.hacker101.com/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Free CTF from HackerOne, paired with the Hacker101 web security video course.',
  },
  {
    name: 'YesWeHack Dojo',
    url: 'https://dojo-yeswehack.com/',
    category: 'CTF Platforms',
    level: 'Intermediate',
    description: 'YesWeHack\'s free CTF training platform, with a new real-world-style challenge each month.',
  },
  {
    name: 'Bugcrowd University',
    url: 'https://www.bugcrowd.com/hackers/bugcrowd-university/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Bugcrowd\'s free, open-source training modules — open to anyone, not just Bugcrowd researchers.',
  },
  {
    name: 'CTFtime',
    url: 'https://ctftime.org/',
    category: 'CTF Platforms',
    level: 'All Levels',
    description: 'The public calendar/directory of CTF competitions happening (or archived) worldwide.',
  },
  {
    name: 'hack.me',
    url: 'https://hack.me/',
    category: 'CTF Platforms',
    level: 'Beginner',
    description: 'Build, host, and share vulnerable web apps in a free sandboxed environment.',
  },
  {
    name: 'PortSwigger Web Security Academy',
    url: 'https://portswigger.net/web-security',
    category: 'Web Application Security',
    level: 'All Levels',
    description: 'Free web security training with hands-on labs explicitly tiered Apprentice → Practitioner → Expert.',
  },
  {
    name: 'OWASP Juice Shop',
    url: 'https://owasp.org/www-project-juice-shop/',
    category: 'Web Application Security',
    level: 'Beginner',
    description: 'OWASP\'s intentionally insecure modern web app — probably the most complete vulnerable app around.',
  },
  {
    name: 'OWASP WebGoat',
    url: 'https://owasp.org/www-project-webgoat/',
    category: 'Web Application Security',
    level: 'Beginner',
    description: 'Deliberately insecure Java web app maintained by OWASP for teaching common vulnerabilities.',
  },
  {
    name: 'DVWA (Damn Vulnerable Web App)',
    url: 'http://www.dvwa.co.uk/',
    category: 'Web Application Security',
    level: 'Beginner',
    description: 'PHP/MySQL app with adjustable difficulty for practicing classic web vulnerabilities.',
  },
  {
    name: 'WebScanTest',
    url: 'http://www.webscantest.com/',
    category: 'Web Application Security',
    level: 'Beginner',
    description: 'A test site for practicing web app vulnerability assessment and scanning.',
  },
  {
    name: 'Hacksplaining',
    url: 'https://www.hacksplaining.com/',
    category: 'Web Application Security',
    level: 'Beginner',
    description: 'Short, plain-language lessons explaining common web vulnerabilities one at a time.',
  },
  {
    name: 'Code Review Lab',
    url: 'https://www.codereviewlab.com/',
    category: 'Web Application Security',
    level: 'Intermediate',
    description: 'Challenges specifically for practicing secure code review.',
  },
  {
    name: 'Pwned Labs',
    url: 'https://pwnedlabs.io/',
    category: 'Cloud Security',
    level: 'Intermediate',
    description: 'Hands-on cloud/AI security labs and cyber ranges across AWS, Azure, GCP, and M365 — free tier available.',
  },
  {
    name: 'flaws.cloud',
    url: 'http://flaws.cloud/',
    category: 'Cloud Security',
    level: 'Beginner',
    description: 'A self-paced AWS security challenge, level by level, with clues along the way.',
  },
  {
    name: 'flaws2.cloud',
    url: 'http://flaws2.cloud/',
    category: 'Cloud Security',
    level: 'Intermediate',
    description: 'flaws.cloud\'s sequel, with both attacker and defender learning paths.',
  },
  {
    name: 'CloudGoat',
    url: 'https://github.com/RhinoSecurityLabs/cloudgoat',
    category: 'Cloud Security',
    level: 'Intermediate',
    description: 'Rhino Security Labs\' "vulnerable-by-design" deployable AWS environment with CTF-style scenarios.',
  },
  {
    name: 'AzureGoat',
    url: 'https://github.com/ine-labs/AzureGoat',
    category: 'Cloud Security',
    level: 'Intermediate',
    description: 'A deliberately vulnerable Azure infrastructure for attack/defense practice.',
  },
  {
    name: 'GCPGoat',
    url: 'https://github.com/ine-labs/GCPGoat',
    category: 'Cloud Security',
    level: 'Intermediate',
    description: 'A deliberately vulnerable Google Cloud Platform infrastructure for hands-on practice.',
  },
  {
    name: 'AWSGoat',
    url: 'https://github.com/ine-labs/AWSGoat',
    category: 'Cloud Security',
    level: 'Intermediate',
    description: 'A damn-vulnerable AWS infrastructure with attack and defense manuals.',
  },
  {
    name: 'IAM Vulnerable',
    url: 'https://github.com/BishopFox/iam-vulnerable',
    category: 'Cloud Security',
    level: 'Advanced',
    description: 'Terraform-built AWS IAM privilege-escalation playground covering 31 attack paths.',
  },
  {
    name: 'Sadcloud',
    url: 'https://github.com/nccgroup/sadcloud',
    category: 'Cloud Security',
    level: 'Advanced',
    description: 'Spins up intentionally vulnerable AWS resources for you to find, unguided.',
  },
  {
    name: 'Crackmes.one',
    url: 'https://crackmes.one/',
    category: 'Reverse Engineering & Binary Exploitation',
    level: 'All Levels',
    description: 'A large library of reverse-engineering challenges (\'crackmes\') at every difficulty level.',
  },
  {
    name: 'exploit.education',
    url: 'https://exploit.education/',
    category: 'Reverse Engineering & Binary Exploitation',
    level: 'Advanced',
    description: 'VMs and challenges for learning memory corruption and binary exploitation (formerly exploit-exercises.com).',
  },
  {
    name: 'CyberDefenders',
    url: 'https://cyberdefenders.org/',
    category: 'Blue Team / Defensive Security',
    level: 'Intermediate',
    description: 'Blue-team-focused labs covering DFIR, threat hunting, and SOC scenarios with real artifacts.',
  },
  {
    name: 'LetsDefend',
    url: 'https://letsdefend.io/',
    category: 'Blue Team / Defensive Security',
    level: 'Beginner',
    description: 'Simulated SOC alert inbox — triage, investigate, and respond to realistic incidents.',
  },
  {
    name: 'Blue Team Labs Online',
    url: 'https://blueteamlabs.online/',
    category: 'Blue Team / Defensive Security',
    level: 'Intermediate',
    description: 'Gamified investigation challenges for defenders: DFIR, security operations, threat hunting.',
  },
  {
    name: 'RangeForce',
    url: 'https://www.rangeforce.com/',
    category: 'Blue Team / Defensive Security',
    level: 'Beginner',
    description: 'Team-oriented cyber readiness platform with a free Community Edition for defensive practice.',
  },
  {
    name: 'InjuredAndroid',
    url: 'https://github.com/B3nac/InjuredAndroid',
    category: 'Android Security',
    level: 'Beginner',
    description: 'CTF-style vulnerable Android app with flags based on real bug bounty findings.',
  },
  {
    name: 'DIVA Android',
    url: 'https://github.com/payatu/diva-android',
    category: 'Android Security',
    level: 'Beginner',
    description: '"Damn Insecure and Vulnerable App for Android" — the classic starting point for Android pentesting.',
  },
  {
    name: 'AndroGoat',
    url: 'https://github.com/satishpatnayak/AndroGoat',
    category: 'Android Security',
    level: 'Intermediate',
    description: 'Kotlin-based vulnerable Android app with guided walkthroughs, covering OWASP Mobile Top 10 issues.',
  },
  {
    name: 'InsecureShop',
    url: 'https://github.com/optiv/InsecureShop',
    category: 'Android Security',
    level: 'Intermediate',
    description: 'An intentionally vulnerable Android shopping app, built in Kotlin.',
  },
  {
    name: 'InsecureBankv2',
    url: 'https://github.com/dineshshetty/Android-InsecureBankv2',
    category: 'Android Security',
    level: 'Intermediate',
    description: 'A vulnerable banking-themed Android app for practicing mobile app security testing.',
  },
  {
    name: 'CTFd',
    url: 'https://ctfd.io/',
    category: 'Open Source Frameworks',
    level: 'All Levels',
    description: 'The open-source platform most CTF organizers actually use to host their own competitions.',
  },
  {
    name: 'MITRE ATT&CK',
    url: 'https://attack.mitre.org/',
    category: 'Open Source Frameworks',
    level: 'All Levels',
    description: 'The open, globally-used knowledge base of real-world adversary tactics and techniques.',
  },
  {
    name: 'GOAD (Game of Active Directory)',
    url: 'https://github.com/Orange-Cyberdefense/GOAD',
    category: 'Open Source Frameworks',
    level: 'Advanced',
    description: 'Open-source, self-hostable, intentionally vulnerable Active Directory environment for AD attack practice.',
  },
  {
    name: 'OWASP Foundation',
    url: 'https://owasp.org/',
    category: 'Open Source Frameworks',
    level: 'All Levels',
    description: 'The nonprofit behind the Top 10, ASVS, Testing Guide, and most open web-security standards in use today.',
  },
  {
    name: 'OWASP MASTG',
    url: 'https://mas.owasp.org/MASTG/',
    category: 'Open Source Frameworks',
    level: 'All Levels',
    description: 'OWASP\'s Mobile Application Security Testing Guide — the open standard for mobile app security testing.',
  },
];

export default resources;
